---
title: try this interaction thing between enterococcus and sweets when taking into
  account the abx interactive effects
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
library(ggridges)
library(brmstools)
library(compositions)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

CLR works with counts, not relab. And also need to add a pseudocount

```{r}
meta <- read_csv('../data/153_combined_META.csv')
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')
cts <- get_counts_subset(meta$sampleid)
cts_ <- cts %>% 
  select(asv_key, sampleid, count)
annot <- asv_annotation_blast_ag %>% 
  filter(asv_key %in% cts_$asv_key)
cts_all <- cts_ %>% 
  left_join(annot %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(cnt = sum(count)) %>% 
  spread('sampleid', 'cnt', fill = 0) %>% 
  filter(!is.na(genus)) %>% 
  column_to_rownames('genus')
```


```{r}
clr_res <- clr(cts_all + 0.5) %>% 
  as.data.frame()  %>% 
  rownames_to_column('genus') %>% 
  gather('sampleid','clr', names(.)[2]:names(.)[ncol(.)])

# the distribution of the transformed counts
# find the median of each genus
clr_medians <- clr_res %>% 
  group_by(genus) %>% 
  summarise(mediangenus = median(clr))

clr_medians %>% gghistogram(x = 'mediangenus')
clr_medians %>% ggboxplot(y = 'mediangenus')

# I need to see the distribution of the actual genus transformed counts
few <- read_csv('../data/087_extra_6_genus_name.csv')

clr_res %>% filter(genus %in% few$genus) %>% 
  gghistogram(x = 'clr', facet.by = 'genus')

clr_res %>% write_csv('../data/171_genus_CLR_res.csv')
```

```{r}
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(mrn = factor(mrn)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
 mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)

clr_few <- clr_res %>% 
  #filter(genus %in% c('Enterococcus')) %>%
  spread('genus','clr')

# still use the log10 cuz that's what I have always been using this time
gcts <- read_csv('../data/088_genus_relab_log10_wide.csv') %>% 
  select(sampleid, Enterococcus)

extra_full <- meta %>% 
  inner_join(clr_few)

clr_entero <- clr_res %>% 
  filter(genus %in% c('Enterococcus'))

extra_entero <- meta %>% 
  inner_join(clr_entero) %>% 
  rename(Enterococcus = clr)
```


```{r}
  
priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
             prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "abx")
            # for the intensity 
            # prior(normal(-3, 1), class = 'b', coef = "intensityablative"),
            # prior(normal(-3, 1), class = 'b', coef = "intensityreduced"),
            # prior(normal(-3, 1), class = 'b', coef = "intensitynonablative")
            )
```




# Enterococcus only

```{r prior}
# prior predictive check
entero_model <- Enterococcus ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)
fitPrior_entero <- brm(entero_model, data=extra_entero, 
                family = 'gaussian',
                prior=priors,  control = list(adapt_delta = 0.99),
           sample_prior = "only")
```


```{r prior}
set.seed(123)
prior_pred_entero <- pp_check(fitPrior_entero, type = "boxplot", nreps = 10, notch = FALSE, alpha = 0) +
  labs(y = 'Enterococcus relative abundance CLR transformed') +
   scale_color_discrete(labels=c('observed distribution', 'simulated from prior predictive distribution')) +
  theme(legend.position = 'bottom', legend.title = element_blank())
  
prior_pred_entero 
```


```{r}
mod_entero =  brm(Enterococcus ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456)

# save it for future use
post_res <- suppressWarnings(posterior_samples(mod_entero)) 
post_res %>%  write_csv('../data/171_entero_model_fg_post_interaction.csv')
```

```{r}
post_res <-   read_csv('../data/171_entero_model_fg_post_interaction.csv')
entero_res <- post_res %>%   
  select(starts_with('b_')) %>% 
  gather('item','coeff') %>% 
  #mutate(grp = if_else(str_detect(item, ':'), 'interaction','single')) %>% 
  ggplot(aes(x = coeff, y = item)) +
  stat_pointinterval(.width = c(.66, .95)) +
  #stat_halfeye() + 
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  #facet_wrap(genus~ grp, scales = 'free') +
  labs(x = ' change per 100g of food',
       y = '', 
       title = 'genus') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "gray40")) +
  theme(axis.text=element_text(size=8, color  = 'black'),
        axis.title=element_text(size=8),
        aspect.ratio=1)

ggsave('../data/171_interaction_model_enterococcus.pdf', width = 8, height = 8)
```
```{r}
# dear god why is it not red!!
post_res %>% select(b_fg_sweets_e) %>% 
  count(b_fg_sweets_e >= 0) %>% 
  mutate(perc = n/4000*100)
```


```{r}
cts <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) 

target_genera <-  cts %>% 
  group_by(genus) %>% 
  count(relab > 0.0001) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(genus)
```


```{r}
 
ret_genus_interaction <- target_genera %>% 
  set_names(target_genera) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue(
              '{genus}  ~ 
               0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | mrn) +
                (1 | timebin)')),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456) 
  })

post_df <- ret_genus_interaction %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) ))  %>% 
  bind_rows(.id = 'genus')  
post_df %>% 
  write_csv('../data/171_genus_foodgroup_model_post_extra_few_interaction.csv')


```

# food only 

```{r}
post <- read_csv('../data/171_genus6_foodgroup_model_post_extra_few_interaction.csv') 

colnames(post)

post %>%   
  select(genus, starts_with('b_')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  mutate(grp = if_else(str_detect(item, ':'), 'interaction','single')) %>% 
  ggplot(aes(x = coeff, y = item, fill = after_stat(x > 0))) +
  stat_pointinterval(.width = c(.66, .95)) + stat_halfeye() + 
  geom_vline(xintercept = 0, col = 'black', linetype = 'dashed') +
  facet_wrap(genus~ grp, scales = 'free') +
  labs(x = ' change per 100g of food',
       y = '', 
       title = 'genus') +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c( "#00BFC4", "#F8766D")) +
  scale_fill_manual(values = c( "#00BFC4", "#F8766D")) +
  theme(axis.text=element_text(size=8, color  = 'black'),
        axis.title=element_text(size=8),
        aspect.ratio=1)

ggsave('../data/171_interaction_model_genus6.pdf', width =23, height = 19)

```

 
```{r}
# make the heatmap with all of the genera 
post_df <- read_csv('../data/171_genus_foodgroup_model_post_extra_few_interaction.csv',  col_select = c(1:25)) %>% 
  select(genus, starts_with('b_'))

key <- read_csv('../data/cleaned_diet_data/food_group_color_key_final.csv', col_types = 'ccccc')

post_res_genera <- post_df %>% 
  select(genus, starts_with('b_')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
 mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
  mutate(shortname = case_when(
    item ==  'milk' ~ 'Milk',
    item == 'meat' ~ 'Meats',
    item ==  'egg' ~ 'Eggs',
    item ==  'legume' ~ 'Legumes',
    item == 'grain' ~ 'Grains',
    item == 'fruit' ~ 'Fruits',
    item == 'veggie' ~ 'Vegetables',
    item ==  'oils' ~ 'Oils', 
    item ==  'sweets' ~ 'Sweets',
    item ==  'milk_e' ~ 'abx + Milk',
    item == 'meat_e' ~ 'abx + Meats',
    item ==  'egg_e' ~ 'abx + Eggs',
    item ==  'legume_e' ~ 'abx + Legumes',
    item == 'grain_e' ~ 'abx + Grains',
    item == 'fruit_e' ~ 'abx + Fruits',
    item == 'veggie_e' ~ 'abx + Vegetables',
    item ==  'oils_e' ~ 'abx + Oils', 
    item ==  'sweets_e' ~ 'abx + Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx'
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))

post_res_genera %>% distinct(shortname)

post_res_genera %>% write_csv('../data/171_post_res_genera.csv')
```
 
```{r}

col_key <- post_res_genera %>% 
  ungroup() %>% 
  distinct(color) %>% 
  pull(color)
names(col_key) <- col_key

genus_fg_main <- ggplot(post_res_genera, aes(x = genus, y = item)) +
  geom_tile(aes(fill = color,  x = genus, y =  item), alpha = 0.5, color='white', width=0.95, height=0.95) +
  geom_text(aes(label = mark, x = genus,y =  item),
            nudge_y = -0.1, nudge_x = 0,size = 3) +
  scale_fill_manual(values = col_key, labels = c('Less than 75% CI crosses 0', '75% CI < 0 negative','75% CI > 0 positive')) +
  theme_pubr() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(angle=50, hjust=1, size=11),
        axis.text.y=element_text(size=11),
        axis.title=element_text(size=axis_title_size),
        #panel.grid.major = element_blank(), 
        #panel.grid.minor = element_blank(),
        legend.position = 'top',
        panel.background=element_rect(colour="black"),
        legend.key = element_rect( colour = "gray50")) 
genus_fg_main 

ggsave('../data/171_genus_main.pdf', width = 15)
```
 
# supp for the intensity as intercept one in enterococcus

```{r}
# the intercept from the enterococcus one with its CLR transformation
entero <- read_csv('../data/171_entero_model_fg_post_interaction.csv')  %>% 
  select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))%>% 
  mutate(shortname = item,
    shortname = case_when(
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    TRUE ~ `shortname`
  ))
 
entero_pt <- entero %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95)) +
  labs(x = 'CLR(Enterococcus) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
         panel.background = element_rect(fill = "#d0cccc",colour = "#d0cccc",size = 0.5, linetype = "solid"),axis.title=element_text(size=10), 
        aspect.ratio=1/3.1)   



S4 <- ggarrange(prior_pred_entero, entero_pt,
          labels = c("A", "B"), align = "v",
          ncol = 1, nrow = 2)

title <- ggdraw() + 
  draw_label(
    "Fig S4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )

combined <- plot_grid(
  title, S4,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(1,3,1,3), "cm"))

ggsave('../data/S4_pp_check_and_intensity_enterococcus_171.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      #plot = combined, 
      dpi = 300)
```

