---
title: "Table 1 making"
output: html_document
date: "2024-08-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(gtsummary)
library(cowplot)
```

```{r}
# finally the below table is comprehensive and deidentified!
PTB <- read_csv('../data/003_combined_PTB_pid.csv')
```
# clean up the info

```{r}
final <- PTB %>% 
  select(age, sex, Disease = disease.simple, source,  intensity, gvhd_ppx) %>% 
  mutate(Disease = case_when(
    Disease == 'NHL' ~ "Non-Hodgkin's lymphoma",
    # Myelodysplastic/myeloproliferative neoplasms
    Disease == 'MDS/MPN' ~ 'MDS/MPN',
    Disease == 'AML' ~ 'Acute myeloid leukemia',
    Disease == 'ALL' ~ 'Acute lymphoid leukemia',
    Disease == 'CLL' ~ 'Chronic lymphocytic leukemia',
    Disease == 'CML' ~ 'Other',
    Disease == 'Hodgkins' ~ "Other",
    Disease == 'Myeloma' ~ 'Myeloma', 
    Disease == 'AA' ~ 'Other',
    Disease == 'other' ~ 'Other'
  )) %>% 
  mutate(source = case_when(
    source == 'unmodified' ~ "Unmodified bone marrow or PBSC",
    source == 'cord' ~ "Cord blood",
    source == 'TCD' ~ "T-cell depleted PBSC"
  )) %>% 
  mutate(sex = case_when(
    sex == 'F' ~ "Female",
    sex == 'M' ~ "Male"
  )) %>% 
  mutate(intensity = case_when(
    intensity == 'nonablative' ~ "Nonmyeloablative",
    intensity == 'ablative' ~ "Ablative",
    intensity == 'reduced' ~ "Reduced intensity"
  )) %>% 
  mutate(gvhd_ppx = case_when(
    gvhd_ppx == 'CNI-based' ~ "CNI-based",
    gvhd_ppx == 'PTCy-based' ~ "PTCy-based",
    gvhd_ppx == 'TCD' ~ "T-cell depleted PBSC"
  ))  %>% 
  mutate(intensity = fct_reorder(intensity, intensity, .fun=length, .desc = T),
         source = fct_reorder(source, source, .fun=length, .desc = T),
         Disease = fct_reorder(Disease, Disease, .fun=length, .desc = T),
         sex = fct_reorder(sex, sex, .fun=length, .desc = T)) %>% 
  rename(`Graft type` = source, 
         #`HCT-CI` = ci,
         `Intensity of conditioning regimen` = intensity ) %>% 
  rename(Sex = sex, Age = age, `GvHD prophylaxis` = gvhd_ppx)

final %>% 
  tbl_summary(
    #type = list(all_double() ~ "continuous"), 
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  bold_labels() %>% 
  as_gt() %>%
  #gt::tab_footnote(footnote = "MDS/MPN = Myelodysplastic/myeloproliferative neoplasms") %>% 
  gt::gtsave(filename = "../data/003_patient_summary.png")
```
# the table 1 figure

```{r}
table1 <- ggdraw() + draw_image("../data/003_patient_summary.png", scale = 0.8)

 title <- ggdraw() + 
  draw_label(
    "Table 1",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )
 

 
combined <- plot_grid(
  title, table1,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/Table_1_patient_summary_003.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  
```

# create another for the 158

```{r}
# create and save the table about patients length of stay     
# load('../data/df_main_Sep18.Rdata')
# link <- read_csv('../../MSS_pipeline-/scripts/food_tree/data/152_pid_match.csv')
# 
# los <- df_main %>%
#   select(mrn, leng_of_stay) %>%
#   full_join(link) %>%
#    select( pid, leng_of_stay)
# 
# los %>% write_csv('../data/003_leng_of_stay_pid.csv')

los <- read_csv('../data/003_leng_of_stay_pid.csv')
meta <- read_csv('../data/153_combined_META.csv')

PTB2 <- PTB %>% 
  full_join(los) %>% 
  # to include only the subset 158
  filter(pid %in% meta$pid)

final2 <- PTB2 %>% 
  select(age, sex, Disease = disease.simple, source,  intensity, gvhd_ppx,day_exposed, leng_of_stay ) %>% 
  mutate(Disease = case_when(
    Disease == 'NHL' ~ "Non-Hodgkin's lymphoma",
    # Myelodysplastic/myeloproliferative neoplasms
    Disease == 'MDS/MPN' ~ 'MDS/MPN',
    Disease == 'AML' ~ 'Acute myeloid leukemia',
    Disease == 'ALL' ~ 'Acute lymphoid leukemia',
    Disease == 'CLL' ~ 'Chronic lymphocytic leukemia',
    Disease == 'CML' ~ 'Other',
    Disease == 'Hodgkins' ~ "Other",
    Disease == 'Myeloma' ~ 'Myeloma', 
    Disease == 'AA' ~ 'Other',
    Disease == 'other' ~ 'Other'
  )) %>% 
  mutate(source = case_when(
    source == 'unmodified' ~ "Unmodified bone marrow or PBSC",
    source == 'cord' ~ "Cord blood",
    source == 'TCD' ~ "T-cell depleted PBSC"
  )) %>% 
  mutate(sex = case_when(
    sex == 'F' ~ "Female",
    sex == 'M' ~ "Male"
  )) %>% 
  mutate(intensity = case_when(
    intensity == 'nonablative' ~ "Nonmyeloablative",
    intensity == 'ablative' ~ "Ablative",
    intensity == 'reduced' ~ "Reduced intensity"
  )) %>% 
  mutate(gvhd_ppx = case_when(
    gvhd_ppx == 'CNI-based' ~ "CNI-based",
    gvhd_ppx == 'PTCy-based' ~ "PTCy-based",
    gvhd_ppx == 'TCD' ~ "T-cell depleted PBSC"
  ))  %>% 
  mutate(intensity = fct_reorder(intensity, intensity, .fun=length, .desc = T),
         source = fct_reorder(source, source, .fun=length, .desc = T),
         Disease = fct_reorder(Disease, Disease, .fun=length, .desc = T),
         sex = fct_reorder(sex, sex, .fun=length, .desc = T)) %>% 
  rename(`Graft type` = source, 
         #`HCT-CI` = ci,
         `Intensity of conditioning regimen` = intensity ) %>% 
  rename(Sex = sex, Age = age, `GvHD prophylaxis` = gvhd_ppx,
         `Days exposed to broad-spectrum antibiotics` = day_exposed,
         `Length of stay at hospital` = leng_of_stay)

final2 %>% 
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})")
  ) %>%
  bold_labels() %>% 
  as_gt() %>%
  gt::gtsave(filename = "../data/003_patient_summary_for_158.png")

summary(PTB2$leng_of_stay)
```

```{r}
table_S1 <- ggdraw() + draw_image("../data/003_patient_summary_for_158.png", scale = 0.8)

title <- ggdraw() + 
  draw_label(
    "Table S1",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )
 

 
combined <- plot_grid(
  title, table_S1,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/Table_S1_patient_summary_158_003.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  
```

