---
title: "PCA variation of the model"
output: html_document
date: "2024-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(ggtext)
library(brms)   
library(ggpubr)
library(tidybayes)
ncores <- parallel::detectCores()
axis_text_size <- 10
```

```{r}
pca_exposure <- read_csv('../data/084_samples_and_PCA.csv')

meta <- read_csv('../data/153_combined_META.csv')
meta_new <- meta %>% 
  full_join(pca_exposure) %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>%    
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0),
         pca = if_else(PCA == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)
```

```{r}
model_PCA <- log(simpson_reciprocal) ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
                pca+
               (1 | pid) +
                (1 | timebin)

priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
             # for the PCA
            prior(normal(0, 0.1), class = 'b', coef = "pca"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

mod_PCA <- brm( model_PCA,  
              data = meta_new, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              control = list(adapt_delta = 0.99),
              chains = 2, 
              seed = 123, sample_prior = T, file = '../data/084_mod_PCA') 


as_draws_df(mod_PCA) %>% write_csv('../data/084_mod_PCA.csv')
```

```{r} 
fg_order <- c( 'Vegetables','abx * Vegetables',
                 'Oils','abx * Oils',
                 'Fruits','abx * Fruits',
                 'Meats','abx * Meats',
                 'Legumes','abx * Legumes',
                 'Eggs','abx * Eggs',
                 'Milk','abx * Milk',
                 'Grains','abx * Grains',
                 'Sweets','abx * Sweets',
                 "TPN" ,"EN" ,'Patient-controlled analgesia', 'abx')

  
matchingtb <- read_rds('../data/196_matching_shortname.rds') %>% 
  mutate(shortname = as.character(shortname)) %>% 
  dplyr::select(-ymin, -ymax) %>% 
  add_row(item = 'b_pca', shortname = 'Patient-controlled analgesia', grp = 'temporal', xmin = -Inf, xmax = Inf, fill_ = 'blue_fill') %>% 
  mutate(shortname = factor(shortname, levels = fg_order)) %>% 
  mutate(id = as.numeric(shortname)) %>% 
  mutate(ymin = id - 0.5,
         ymax = id + 0.5) 

fg <- read_csv('../data/084_mod_PCA.csv') %>% 
  dplyr::select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  inner_join(matchingtb)
```


```{r} 
cross0 <- fg %>%
   filter(grp == 'temporal') %>%
  group_by(item) %>%
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>%
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))

post_PCA <- fg %>% 
  filter(grp == 'temporal') %>% 
  left_join(cross0) %>% 
  ggplot() +
 stat_pointinterval(aes(x = coeff, y = shortname, color = Cross),.width = 0.95, fatten_point = 1.2) +
  geom_rect(data = matchingtb, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill_), alpha = .1) +
  scale_fill_manual(values=c("interaction_fill" = "tan2", "blue_fill" = "#FAEFD1")) +
  geom_vline(xintercept = 0, col = 'blue',  size = 1) +
  labs(x = 'ln(diversity) change', y = '') +
  scale_y_discrete( labels = function(x) { ifelse(str_detect(x, '\\*'),  str_glue("<b style='color:royalblue'>{x}</b>"), as.character(x)) }) +
  theme_classic() +
  scale_color_manual(values = c( "red", "black")) +
  guides(fill = "none") +
  theme(axis.text = element_text( size = 10), axis.text.y = element_markdown(),
        plot.background = element_rect(fill='transparent', color=NA), legend.position = 'none',
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)

post_PCA  
```



```{r} 
library(cowplot)

title <- ggdraw() + 
  draw_label(
    "Fig. S9",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme( plot.margin = margin(0, 0, 0, 0))

 
combined <- plot_grid(
  title, post_PCA,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(1,4,4,4), "cm"))

ggsave('../data/084_pca_diversity.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      plot = combined, 
      dpi = 300)
```