---
title: "Top 10 eaten foods of the sweets group"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
dtb <- read_csv('../data/152_combined_DTB.csv')
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

```{r}
# the top 10 most consumed in  , sweets 
# total number of meals 
n_meal <- dtb %>% 
  count(pid, fdrt, Meal) %>% 
  nrow()
  
top3grp <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_per_code = sum(dehydrated_weight)) %>% 
  group_by(fgrp1) %>% 
  arrange(desc(total_per_code), .by_group = T)  %>% 
  top_n(10) %>% 
  left_join(key) %>% 
  ungroup() %>% 
  mutate(fg1_full_name = case_when(
    fgrp1 == '9' ~ 'Sugars, Sweets & Beverages'
  )) %>% 
  mutate(fg1_full_name = factor(fg1_full_name, levels = c( 'Sugars, Sweets & Beverages'))) %>% 
  group_by(fg1_full_name) %>% 
  arrange(total_per_code, .by_group = T)
```

```{r}
# or I just calculate the sugar in percent in those food code
top3grp_sugar <- dtb %>% 
  mutate(fgrp1 = str_sub(Food_code, 1,1)) %>% 
  filter(fgrp1 %in% c('9')) %>% 
  group_by(Food_code, description, fgrp1) %>% 
  summarise(total_sugar_per_code = sum(Sugars_g)) %>% 
  ungroup() %>% 
  inner_join(top3grp) %>% 
  mutate(description = factor(description, levels = top3grp$description))

# to calculate a per meal average of the top 10 foods when the meal actually contains this food code
# to calculate the number of effective meals (that is the meal that contains this food code)
contains <- dtb %>% 
  filter(Food_code %in% top3grp$Food_code) %>% 
  distinct(Food_code, pid, fdrt, Meal) %>% 
  count(Food_code) %>% 
  full_join(top3grp %>% select(Food_code, description, total_per_code)) %>% 
  mutate(eff_per_meal_ave = round(total_per_code/n, 2)) %>% 
  full_join(top3grp_sugar %>% select(Food_code, total_sugar_per_code)) %>% 
  mutate(eff_per_meal_sugar = round(total_sugar_per_code/n, 2)) 


bars <- contains %>% 
  select(description,eff_per_meal_ave, eff_per_meal_sugar ) %>% 
  gather('grp','gram',eff_per_meal_ave: eff_per_meal_sugar) %>% 
  mutate(grp = if_else(grp == 'eff_per_meal_sugar', 'Sugar content', 'Total') ) %>% 
  mutate(grp = factor(grp, levels = c('Sugar content','Total'))) %>% 
  mutate(description = str_wrap(description, indent = 4, width = 30))

# how to sort the bars 
order_eff <- bars %>% 
  filter(grp == 'Total') %>% 
  arrange(gram) %>% 
  pull(description)


plot_eff <- bars %>% 
  mutate(description = factor(description, levels = order_eff)) %>% 
  ggbarplot( "description", "gram",
                  xlab = '',ylab = 'Effective per-meal average consumption\nin dehydrated weight (grams)',
  fill = "grp", color = "grp", palette = c( "#ffbcdc", "#db2589"),
  width = 0.7, 
  position = position_dodge(0.8)) +
  coord_flip() +
  theme(
        axis.text.y = element_text(size=10),
        legend.position = 'bottom',
        legend.title= element_blank())
plot_eff

```


```{r}
title <- ggdraw() + 
  draw_label(
    "Fig. S6",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )
  

combined <- plot_grid(
  title, plot_eff,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,3,6,1), "cm"))
 
ggsave('../results//S06_top10_eaten_foods_of_sweets_099.pdf',  width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)

```


