---
title: Interaction model between enterococcus and sweets when taking into
  account the abx interactive effects
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
library(ggridges)
library(brmstools)
library(compositions)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

CLR works with counts, not relab. And also need to add a pseudocount

```{r}
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
 mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)
```


```{r}
library(vdbR)
connect_database('~/dbConfig.txt')
get_table_from_database('asv_annotation_blast_ag')
cts <- get_counts_subset(meta$sampleid)
cts_ <- cts %>% 
  select(asv_key, sampleid, count)
```



```{r}
library(tidyverse)
library(ggpubr)
library(vdbR)
connect_database()
list_table_from_database('asv')
get_table_from_database('asv_annotation_blast_detailed_ag')

meta <- read_csv('../data/153_combined_META.csv')
details <- get_counts_subset(meta$sampleid)

detailsall <- details %>% 
  inner_join(asv_annotation_blast_detailed_ag %>% select(asv_key : pident_97)) %>% 
  distinct(asv_key, pident)

detailsall %>% count(pident > 97) %>% 
  mutate(perc = round(n/sum(n)*100,2))

# the asv that has pident > 97
# for genus!
asv_97 <- detailsall %>% 
  filter(pident > 97)

asv_97 %>% write_csv('../data/171_asv_with_pident_gt_97.csv')
```

```{r}
# only count the asvs that have pident > 97
quality_asv <- read_csv('../data/171_asv_with_pident_gt_97.csv') %>% 
  pull(asv_key)

annot <- asv_annotation_blast_ag %>% 
  select(asv_key, genus) %>% 
  mutate(genus = if_else(asv_key %in% quality_asv, genus, NA))
  

  
cts_all <- cts_ %>% 
  left_join(annot %>%  select(asv_key, genus), by  = 'asv_key') %>% 
  group_by(sampleid, genus) %>% 
  summarise(cnt = sum(count)) %>% 
  spread('sampleid', 'cnt', fill = 0) %>% 
  filter(!is.na(genus)) %>% 
  column_to_rownames('genus')

clr_res <- clr(cts_all + 0.5) %>% 
  as.data.frame()  %>% 
  rownames_to_column('genus') %>% 
  gather('sampleid','clr', names(.)[2]:names(.)[ncol(.)])

clr_res %>% write_csv('../data/171_genus_CLR_res.csv')
```


```{r}
clr_res <- read_csv('../data/171_genus_CLR_res.csv')

clr_wide <- clr_res %>% 
  spread('genus','clr')

extra_full <- meta %>% 
  inner_join(clr_wide)  
```

```{r} 
# 
# # still use the log10 cuz that's what I have always been using this time
# gcts <- read_csv('../data/090_all_samples1009_meta_p2d_fg9_dietall_genera90_pid.csv') %>% 
#   select(sampleid, Enterococcus)
```


```{r}
  
priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
             prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "abx")
            )
```

# Enterococcus only

```{r}
mod_entero =  brm(Enterococcus ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, file = '../data/171_mod_entero_interaction')

# save it for future use
post_res <- suppressWarnings(posterior_samples(mod_entero)) 
post_res %>%  write_csv('../data/171_entero_model_fg_post_interaction.csv')
```


  

```{r}
cts <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  filter(sampleid %in% meta$sampleid) 

target_genera <-  cts %>% 
  group_by(genus) %>% 
  count(relab > 0.002) %>% 
  rename(criteria = names(.)[2]) %>% 
  filter(criteria == 'TRUE') %>% 
  arrange(-n) %>% 
  filter(genus != 'NA') %>% 
  mutate(perc = round(n/nrow(meta)*100, 0)) %>% 
  filter(perc > 10) %>% 
  pull(genus)
```

# fg genera

```{r}
 
ret_genus_interaction <- target_genera %>% 
  set_names(target_genera) %>% 
  purrr::map(function(genus) {
    mod =  brm( as.formula(str_glue(
              '{genus}  ~ 
               0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)')),  
                data = extra_full, 
              warmup = 1000, iter = 3000, 
              prior = priors,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456) 
  })

post_df <- ret_genus_interaction %>% 
  imap(~ (suppressWarnings(posterior_samples(.x)) ))  %>% 
  bind_rows(.id = 'genus')  
post_df %>% 
  write_csv('../data/171_target_genus_fg_model_post_interaction.csv')


```

 
```{r}
# make the heatmap with all of the genera 
post_df <- read_csv('../data/171_genus_foodgroup_model_post_extra_few_interaction.csv',  col_select = c(1:25)) %>% 
  select(genus, starts_with('b_'))

key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')

post_res_genera <- post_df %>% 
  select(genus, starts_with('b_')) %>% 
  gather('item','coeff', names(.)[2]:names(.)[ncol(.)]) %>% 
  group_by(genus, item) %>% 
  summarise(q50 = median(coeff),
            q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975),
            q12.5 = quantile(coeff, probs = 0.125),
            q87.5 = quantile(coeff, probs = 0.875),
            q1.25 = quantile(coeff, probs = 0.0125),
            q98.75 = quantile(coeff, probs = 0.9875),
            q0.5 = quantile(coeff, probs = 0.005),
            q99.5 = quantile(coeff, probs = 0.995)
            ) %>% 
  ungroup() %>% 
  mutate(mark = if_else(q99.5 < 0 | q0.5 > 0, '***', if_else(q98.75 < 0 | q1.25 > 0, '**', if_else(q97.5 < 0 | q2.5 > 0, '*', '')))) %>% 
  mutate(color = if_else(q87.5 < 0, 'steelblue', if_else(q12.5 > 0, 'maroon', 'white'))) %>% 
 mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
  mutate(shortname = case_when(
    item ==  'milk' ~ 'Milk',
    item == 'meat' ~ 'Meats',
    item ==  'egg' ~ 'Eggs',
    item ==  'legume' ~ 'Legumes',
    item == 'grain' ~ 'Grains',
    item == 'fruit' ~ 'Fruits',
    item == 'veggie' ~ 'Vegetables',
    item ==  'oils' ~ 'Oils', 
    item ==  'sweets' ~ 'Sweets',
    item ==  'milk_e' ~ 'abx + Milk',
    item == 'meat_e' ~ 'abx + Meats',
    item ==  'egg_e' ~ 'abx + Eggs',
    item ==  'legume_e' ~ 'abx + Legumes',
    item == 'grain_e' ~ 'abx + Grains',
    item == 'fruit_e' ~ 'abx + Fruits',
    item == 'veggie_e' ~ 'abx + Vegetables',
    item ==  'oils_e' ~ 'abx + Oils', 
    item ==  'sweets_e' ~ 'abx + Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx'
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))

post_res_genera %>% distinct(shortname)

post_res_genera %>% write_csv('../data/171_post_res_genera.csv')
```
 
# marginal Enterococcus

```{r}
clr_res <- read_csv('../data/171_genus_CLR_res.csv')
clr_Enterococcus <- clr_res %>% 
  filter(genus %in% c('Enterococcus')) %>%
  spread('genus','clr')

meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid)) %>% 
  inner_join(clr_Enterococcus)

entero_model_original <- Enterococcus ~ 0 +
             intensity+
                empirical+
               fg_fruit:empirical+
                fg_meat:empirical+
                fg_milk:empirical+
                fg_oils:empirical+
                fg_egg:empirical+
                fg_grain:empirical+
                fg_sweets:empirical+
                fg_legume:empirical+
                fg_veggie:empirical+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)
get_prior(formula = entero_model_original, data = meta)

  
priors_enterococcus_original <- c(# for the food group variables
           prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_veggie"),
            # interaction terms
           # interaction terms
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_veggie"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE")
            
            )
```


```{r}
mod_entero =  brm(entero_model_original,  
                data = meta, 
              warmup = 1000, iter = 3000, 
              prior = priors_enterococcus_original,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, file = '../data/171_mod_entero_interaction_original')
```


```{r}
dat_conditional_mod_entero <- conditional_effects(mod_entero, surface = T)

condi_dat_mod_entero <- dat_conditional_mod_entero %>% 
  keep(.p = str_detect(names(.), ':')) %>% 
  bind_rows(.id = 'grp') %>% 
  mutate(grp = str_replace(grp, '\\:empirical','')) %>% 
  left_join(key %>% select(grp = fg1_name, shortname)) %>% 
  mutate(shortname = factor(shortname, levels = rev( c('Vegetables',
                 'Oils',
                 'Fruits',
                 'Meats',
                 'Legumes',
                 'Eggs',
                 'Milk',
                 'Grains',
                 'Sweets'))))

library(wesanderson) 
# the color for the strip background
palette <- wes_palette("Royal1", 2)
strip_color <- wes_palette("Royal1", 3)[3]
```


```{r}
conditional9_entero <- condi_dat_mod_entero %>%   
  ggplot() +
  geom_smooth(aes(x = effect1__, y = estimate__, ymin = lower__, ymax = upper__, fill = effect2__, color = effect2__),
              stat = "identity",
              alpha = .3, linewidth = 1.5)+ 
  scale_fill_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  scale_colour_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  facet_wrap(~ shortname, nrow = 3, scales = 'free_x') +
  labs(y = 'Predicted CLR(Enterococcus)', x = 'Food group consumed (grams)') +
  theme_classic() +
  theme(legend.position = 'top', legend.title = element_text(size = 8, face="bold"),
        legend.text = element_text( size=8, face="bold"),
        legend.background=element_rect(fill = alpha("white", 0)),
       legend.key=element_rect(fill = alpha("white", 0)),
        aspect.ratio = 1, 
        strip.background = element_rect(color="white", fill=strip_color, size=1.5,linetype="solid"),
     axis.text=element_text(size=8), axis.title=element_text(size=axis_text_size))    +
  guides(fill = guide_legend(direction = "vertical"), color = guide_legend(direction = "vertical"))
#conditional9_entero   

title <- ggdraw() + 
  draw_label(
    "Fig. S13",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0)
  )

combined <- plot_grid(
  title, conditional9_entero,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(2,2,5,2), "cm"))

ggsave('../data/S13_conditional9_entero_171.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  

```