---
title: "Interaction model with diversity"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(1)
library(tidyverse)
library(brms)   
library(ggpubr)
library(tidybayes)
library(cowplot)
library(ggridges)
library(brmstools)
library(bayesplot)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
dtb <- read_csv('../data/152_combined_DTB.csv') 
range(dtb$fdrt)
```

# the interaction model with diversity

```{r}
meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid)) %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100) %>% 
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,  
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx)

```


```{r}
div_model  <- log(simpson_reciprocal) ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)
get_prior(div_model,data = meta )

```

```{r}
div_priors <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )
```


```{r}
model_div <- brm( div_model,  
              data = meta, 
              warmup = 1000, iter = 3000, 
              prior = div_priors,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T) 

# actually draw samples from the priors 
samples_prior <- prior_draws(model_div)
# save it for future use
post_res <- suppressWarnings(posterior_samples(model_div)) 
post_res %>%  write_csv('../results/173_div_model_fg_post_interaction.csv')
```


# use conditional_effects function to see the marginal effects  
 
```{r}

# I wanna use the original data types for this thing
meta_original <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid)) 


mod_original <- log(simpson_reciprocal) ~ 0 +        
                intensity+
                empirical+
               fg_fruit:empirical+
                fg_meat:empirical+
                fg_milk:empirical+
                fg_oils:empirical+
                fg_egg:empirical+
                fg_grain:empirical+
                fg_sweets:empirical+
                fg_legume:empirical+
                fg_veggie:empirical+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)

get_prior(mod_original,data = meta_original )

div_priors_original <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalFALSE:fg_veggie"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "empiricalTRUE:fg_veggie"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "ENTRUE"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

model_div_original <- brm( mod_original,  
              data = meta_original, 
              warmup = 1000, iter = 3000, 
              prior = div_priors_original,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T)
```

```{r}
dat_conditional <- conditional_effects(model_div_original, surface = T)

condi_dat <- dat_conditional %>% 
  keep(.p = str_detect(names(.), ':')) %>% 
  bind_rows(.id = 'grp')     

condi_dat %>% write_csv('../intermediate_data/173_conditional_data.csv')
```


# prior predictive check  

```{r}
fitPrior <- brm(div_model, data=meta, 
                family = 'gaussian',
                prior=div_priors, seed = 123,
           sample_prior = "only")
# the below is the posterior predictive check 
prior_c <- pp_check(fitPrior, type = "scatter_avg", ndraws = 100)$data
```


```{r}
set.seed(8)
prior_pred <- pp_check(fitPrior, ndraws = 500, alpha = 0.1) +
  labs(y = 'log(microbiome alpha diversity)',
       title = 'Prior predictive check') +
   scale_color_discrete(labels=c('observed distribution', 'simulated from prior predictive distribution')) +
  theme(legend.position = 'bottom', legend.title = element_blank())
  
prior_pred 
ggsave('../intermediate_data/173_Prior_pred_check.pdf')
```

# for the S4
# posterior predictive check 

```{r}
fit <- brm(div_model, data=meta, 
                prior=div_priors, 
           sample_prior = "no", seed = 12)

post_pred <- pp_check(fit, type = "boxplot", nreps = 10, notch = FALSE, alpha = 0)+
  labs(y = 'log(microbiome alpha diversity)',
       title = 'Posterior predictive check') +
   scale_color_discrete(labels=c('observed distribution', 'simulated from posterior predictive distribution')) +
  theme(legend.position = 'bottom', legend.title = element_blank())
post_pred 
```

```{r} 
S4 <- plot_grid(prior_pred, NA,post_pred,
          labels = c("A",NA, "B"), align = "v",rel_heights = c(1,0.2,1),
          #label.y = 1,
          ncol = 1)
 
title <- ggdraw() + 
  draw_label(
    "Fig. S4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 7)
  )
 
combined <- plot_grid(
  title, S4,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(2,3,3,3), "cm"))
 
ggsave('../results/S04_prior_and_post_pred_173.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      plot = combined, 
      dpi = 300) 
```

# the random intercepts of the week relative to transplant 

```{r}
random_effects_timebin <- post_res %>% 
  select(starts_with('r_timebin')) %>% 
  gather('timebin','coeff') %>% 
  mutate(timebin = str_replace(timebin, 'r_timebin\\[',''),
         timebin = str_replace(timebin, ',Intercept\\]','')) 
  

week_ids <- tibble(
  timebin = random_effects_timebin %>% distinct(timebin) %>% pull(timebin),
  weekID = c(c(-2, -1), seq(1, 8))
) %>% 
  mutate(weekID = str_glue('Week {weekID}'))
week_ids 
 
random_effects_timebin_df <- random_effects_timebin %>% 
  left_join(week_ids)
```
```{r}
ggplot(random_effects_timebin_df, aes(x = coeff, y = weekID)) +
   stat_pointinterval( .width = 0.95, fatten_point = 1.5) +
  coord_flip() +  # Flip coordinates for horizontal display
  theme_pubr() +
  labs(y = "Week Relative to Transplant", x = "Random Intercept", 
       title = "Caterpillar Plot of Random Intercepts for Week") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1 ), aspect.ratio = 1)
  

```


