---
title: "New interaction model results"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# params

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
library(ggtext)
library(tidybayes)
axis_text_size <- 10
axis_title_size <- 10
zero_line_size = .8
META <- read_csv('../data/153_combined_META.csv')
```

# 2D

```{r}
macro <- read_csv('../data/090_model_alpha_macro_fat_post_interaction.csv')
fg <- read_csv('../data/171_div_model_fg_post_interaction.csv')

fg_order <- c( 'Vegetables','abx * Vegetables',
                 'Oils','abx * Oils',
                 'Fruits','abx * Fruits',
                 'Meats','abx * Meats',
                 'Legumes','abx * Legumes',
                 'Eggs','abx * Eggs',
                 'Milk','abx * Milk',
                 'Grains','abx * Grains',
                 'Sweets','abx * Sweets',
                 "TPN" ,"EN" , 'abx')

key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')

fg_label <- tibble(ord = fg_order) %>% 
  mutate(shortname = str_replace(ord, 'abx \\+ ','')) %>% 
  left_join(key %>% select(shortname, color)) %>% 
  mutate(color = if_else(is.na(color), 'black', color))


# to clean the y labels in both of the df
cleaned_fg <- fg  %>% select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_fg_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
   mutate(fgrp1 = case_when(
    item ==  'milk' ~ '1',
    item == 'meat' ~ '2',
    item ==  'egg' ~ '3',
    item ==  'legume' ~ '4',
    item == 'grain' ~ '5',
    item == 'fruit' ~ '6',
    item == 'veggie' ~ '7',
    item ==  'oils' ~ '8', 
    item ==  'sweets' ~ '9'
  ))  %>% 
  left_join(key %>% select(fgrp1, color, shortname)) %>% 
  mutate(shortname = case_when(
        item ==  'milk_e' ~ 'abx * Milk',
    item == 'meat_e' ~ 'abx * Meats',
    item ==  'egg_e' ~ 'abx * Eggs',
    item ==  'legume_e' ~ 'abx * Legumes',
    item == 'grain_e' ~ 'abx * Grains',
    item == 'fruit_e' ~ 'abx * Fruits',
    item == 'veggie_e' ~ 'abx * Vegetables',
    item ==  'oils_e' ~ 'abx * Oils', 
    item ==  'sweets_e' ~ 'abx * Sweets',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx',
    TRUE ~ `shortname`
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal'))

# find the credible interval of the abx line
cleaned_fg %>% filter(str_detect(shortname, 'abx')) %>% 
  group_by(shortname) %>% 
  tidybayes::median_qi(coeff , .width = c( .95)) %>% 
  mutate(coeff = round(coeff, 2),
         .lower = round(.lower, 2),
         .upper = round(.upper, 2))
```

```{r}
# I need to create a data frame that has the coordinates of the rectangles that I wanna create
interaction_terms <- tibble(
  shortname = fg_label$ord
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         interaction_fill = 'interaction_fill')

# this leaves me no choice but I need to fill the other blue area with the blue rectangles 
blue_terms <- tibble(
  shortname = fg_label$ord
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(!str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         blue_fill = 'blue_fill')
```

### fg plot

```{r}
cross0 <- cleaned_fg %>%
   filter(grp == 'temporal') %>% 
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))

fg_temporal <- cleaned_fg %>% 
  filter(grp == 'temporal') %>% 
  mutate(shortname = factor(shortname, levels = fg_label$ord)) %>% 
  left_join(cross0) %>% 
  ggplot() +
   stat_pointinterval(aes(x = coeff, y = shortname, col = Cross), .width = .95, fatten_point = 1.2) +
  geom_rect(data = interaction_terms, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = interaction_fill), alpha = .1) +
  geom_rect(data = blue_terms, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = blue_fill) , alpha = .1) +
  scale_fill_manual(values=c("interaction_fill" = "lightblue", "blue_fill" = "royalblue")) +
  scale_color_manual(values = c("#EC0000", "black")) +
  scale_y_discrete( labels = function(x) { ifelse(str_detect(x, '\\*'),  str_glue("<b style='color:royalblue'>{x}</b>"), as.character(x)) }) +
  geom_vline(xintercept = 0, col = 'blue', size = zero_line_size) +
  labs(x = 'ln(diversity) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
        axis.text.y = element_markdown(),
        plot.background = element_rect(fill='transparent', color=NA), 
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)      
fg_temporal         
```


```{r fg_pt} 
# the fg  patient
fg_pt <- cleaned_fg %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = c(.66, .95), fatten_point = 1.2) +
  labs(x = 'Conditioning intercept [ln(diversity)]', y = '') +
   xlim(0.9, 3) +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
         panel.background = element_rect(fill = "gray95",colour = "gray95",size = 0.5, linetype = "solid"),axis.title=element_text(size=10), 
        aspect.ratio=1.3)

ggsave('../data/f2c_176.pdf',
      width = 80, height = 120, units = "mm", device = 'pdf', 
      plot = fg_pt, 
      dpi = 300)
```
```{r}
# the credible interval for the intensity
cleaned_fg %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  group_by(item) %>% 
  tidybayes::median_qi(coeff , .width = c(.95)) %>% 
  mutate(coeff = round(coeff, digits = 2), 
         .lower = round(.lower, digits = 2), 
         .upper = round(.upper, digits = 2) )
```


```{r fg_pt} 
# assemble the ones for the fg
fg_side <-  plot_grid(fg_temporal,NA,
                rel_heights = c(3,.1),align = 'vh',axis = 'lrtb',
                 nrow = 2)
fg_side
```

# 2E

```{r}
# order the macro panel

cleaned_macro <-  macro %>% select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  mutate(item = str_replace(item, 'b_ave_',''),
         item = str_replace(item, 'b_',''),
         item = str_replace(item, 'intensity','')) %>% 
  mutate(shortname = case_when(
        item ==  'fiber_e' ~ 'abx * Fiber',  
    item == 'fiber' ~ 'Fiber',
    item ==  'fat_e' ~ 'abx * Fat',
    item ==  'fat' ~ 'Fat',
    item == 'Sugars_e' ~ 'abx * Sugars',
    item == 'Sugars' ~ 'Sugars',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx'
  )) %>% 
  mutate(grp = if_else(item %in% c('nonablative','reduced','ablative'), 'patient', 'temporal')) %>% 
  mutate(grp = factor(grp, levels = c('temporal','patient')))

cleaned_macro %>% distinct(item) %>% pull(item)
# sort them by the order of the left side of middle q66
macro_e_order <- cleaned_macro %>% filter(str_detect(item, '_e$')) %>% 
  group_by(shortname) %>% 
  tidybayes::median_qi(coeff , .width = c( .66)) %>% 
  arrange(.lower) %>% pull(shortname)

cross0_macro <- cleaned_macro %>%
   filter(grp == 'temporal') %>% 
  group_by(item) %>% 
  summarise(q2.5 = quantile(coeff, probs = 0.025),
            q97.5 = quantile(coeff, probs = 0.975)) %>% 
  mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))


macro_order <- tibble(
  shortname = c('Fat','abx * Fat',
                 'Fiber','abx * Fiber',
                 'Sugars','abx * Sugars',
                 "TPN" ,"EN" , 'abx')
) %>% inner_join(cleaned_macro %>% distinct(item, shortname)) %>% 
  inner_join(cross0_macro %>% select(item, Cross))

# to find the intervals of those terms
cleaned_macro %>% filter(str_detect(shortname, 'abx')) %>% 
  group_by(shortname) %>% 
  tidybayes::median_qi(coeff , .width = c( .95)) %>% 
  mutate(coeff = round(coeff, 2),
         .lower = round(.lower, 2),
         .upper = round(.upper, 2))

interaction_terms_macro <- tibble(
  shortname = macro_order$shortname
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         interaction_fill = 'interaction_fill')

blue_terms_macro <- tibble(
  shortname = macro_order$shortname
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(!str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         blue_fill = 'blue_fill')

```
 

#### macro plot
 
```{r}
macro_temporal <- cleaned_macro %>% 
  filter(grp == 'temporal') %>% 
  mutate(shortname = factor(shortname, levels = macro_order$shortname)) %>% 
  left_join(cross0_macro)  %>% 
  ggplot() +
  stat_pointinterval(aes(x = coeff, y = shortname, col = Cross),.width = .95, fatten_point = 1.2) +
 geom_rect(data = interaction_terms_macro, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = interaction_fill), alpha = .3) +
  geom_rect(data = blue_terms_macro, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = blue_fill) , alpha = .1) +
  scale_fill_manual(values=c("interaction_fill" = "#6B8E2320", "blue_fill" = "#6B8E2340")) +
  geom_vline(xintercept = 0, col = 'blue', size = zero_line_size) +
  labs(x = 'ln(diversity) change', y = '') +
  # doing magic to change the text appearance for interaction terms!
  scale_y_discrete( labels = function(x) { ifelse(str_detect(x, '\\*'),  str_glue("<b style='color:royalblue'>{x}</b>"), as.character(x)) }) +
  theme_classic() +
  theme(legend.position = 'none') +
  scale_color_manual(values = c("#EC0000", "black")) +
  theme(
        plot.background = element_rect(fill='transparent', color=NA), 
        axis.title=element_text(size=10), 
        #axis.text.y = element_text( size = 10),
        axis.text.y = element_markdown(),
        #panel.background = element_rect(fill = "#d8dcec",colour = "#d8dcec",size = 0.5, linetype = "solid"),
        aspect.ratio=1/1.5)
macro_temporal
```
# 2C intensity

```{r macro_pt}
macro_pt <- cleaned_macro %>% 
  filter(grp == 'patient') %>% 
  mutate(shortname = factor(shortname, levels = c('Nonablative','Reduced','Ablative'))) %>% 
  ggplot(aes(x = coeff, y = shortname)) +
  stat_pointinterval(.width = .95, fatten_point = 1.2) +
  labs(x = 'Conditioning intercept [ln(diversity)]', y = '') +
   xlim(1.5, 2.5) +
  scale_x_continuous( breaks = seq(1.4, 2.4, 0.2)) + 
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
          panel.background = element_rect(fill = "gray96",colour = "gray96",size = 0.5, linetype = "solid"),
        axis.title=element_text(size=10), 
        aspect.ratio=1.4)
macro_pt

```


```{r macro_pt}
macro_side <-  plot_grid(macro_pt,NA, macro_temporal,
                rel_heights = c(1,-.8, 1.9),align = 'hv',axis = 'lrtb',
                labels = c('C',NA, 'D'),label_y = .7,
                 ncol = 1 )
macro_side   
```


# 2A

```{r f2a}
twoscore <- read_csv('../data/086_twoscore_procrustes.csv') 

f2a <- twoscore %>%  
  mutate(pNd = str_extract(pNd, '\\d')) %>% 
  arrange(desc(grp)) %>% 
  mutate(pNd =  factor(pNd)) %>% 
  ggplot(aes(x = pNd, y = score, group = grp, linetype = grp)) +
  geom_line(size = 0.3) +
  geom_point(size = 1.3) +
  labs(x = 'Number of previous days\nof dietary intake',y = 'Procrustes score') +
  scale_linetype_manual(values = c('solid','dashed')) +
  theme_classic()  +
  theme(aspect.ratio=1.3,
        legend.position = 'none',
        axis.text=element_text(size=axis_text_size), 
        axis.title=element_text(size=axis_text_size),
        legend.title = element_blank(), 
        axis.text.x = element_text(angle=0, hjust=0.5)) 
f2a
ggsave('../data/f2a_176.pdf',
      width = 40, height = 70, units = "mm", device = 'pdf', 
      plot = f2a, 
      dpi = 300)
```


# 2B

```{r diagram}
p <- '../data/cartoon_of_model.png'
diagram <- ggdraw() +
  draw_image(magick::image_read(p),   scale =.9 ,hjust = -.05) 
diagram
```


```{r}
# the conditional effects plot
library(wesanderson) 
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
conditional <- read_csv('../data/173_conditional_data.csv') %>% 
  mutate(grp = str_replace(grp, '\\:empirical','')) %>% 
  left_join(key %>% select(grp = fg1_name, shortname)) %>% 
  mutate(shortname = factor(shortname, levels = rev( c('Vegetables',
                 'Oils',
                 'Fruits',
                 'Meats',
                 'Legumes',
                 'Eggs',
                 'Milk',
                 'Grains',
                 'Sweets'))))
palette <- wes_palette("Royal1", 2)
# the color for the strip background
strip_color <- wes_palette("Royal1", 3)[3]
``` 

# 2G condi fg

```{r conditional9}      
conditional9 <- conditional %>%   
  ggplot() +
  geom_smooth(aes(x = effect1__, y = estimate__, ymin = lower__, ymax = upper__, fill = effect2__, color = effect2__),
              stat = "identity",
              alpha = .3, linewidth = 1.5)+ 
  scale_fill_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  scale_colour_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  facet_wrap(~ shortname, nrow = 2, scales = 'free_x') +
  ylim(0, 3.3) +
  labs(y = 'Predicted log(diversity)', x = 'Food group consumed (grams)') +
  theme_classic() +
  theme(legend.position = 'none', legend.title = element_text(size = 8, face="bold"),
        legend.text = element_text( size=8, face="bold"),
        panel.background = element_rect(fill = "#FAEFD140"),
        legend.background=element_rect(fill = alpha("white", 0)),
       legend.key=element_rect(fill = alpha("white", 0)),
        aspect.ratio = 1/1.5, 
        strip.background = element_rect(color="white", fill=strip_color, size=1.5,linetype="solid"),
     axis.text=element_text(size=8), axis.title=element_text(size=axis_text_size))    +
  guides(fill = guide_legend(direction = "vertical"), color = guide_legend(direction = "vertical"))
#conditional9          
``` 

# 2H condi macro

```{r}
conditional3 <- read_rds('../data/090_conditional3.RDS')
```

## condiall

```{r}
# put the conditional for the fg and macronutrients together
condiall <- plot_grid(conditional9, conditional3,
                      labels = c('G', 'H'),label_y = 1,
                align = 'h',axis = 'l', rel_heights = c(2,1.1),
                  ncol = 1)
condiall   
```


# 2F

```{r}
# making a df for annotating the number of samples and patients in the two groups

num_annot <- META %>% 
  split(.$empirical) %>% 
  imap_dfr(function(df, name_) {
    df %>% distinct(pid) %>% nrow
  }) %>% gather('empirical','pt_num') %>% 
  full_join(META %>% count(empirical) %>% mutate(empirical = as.character(empirical))) %>% 
  rename(sample_num = n) %>% 
  mutate(antibiotics = if_else(empirical == 'FALSE', 'not exposed', 'exposed')) %>% 
  mutate(lbl = str_glue('{sample_num} samples\nfrom {pt_num} patients'))
num_annot
```
```{r}
# Sample data (replace with your actual data)
data <- data.frame(
  x = rnorm(30),
  y = rnorm(30),
  group1 = rep(c("A", "B"), each = 15),
  group2 = rep(c("X", "Y"), 15)
)

# Base plot with facet_grid
p <- ggplot(data, aes(x, y)) +
  geom_point() +
  facet_grid(group1 ~ group2)

# Data frame with labels and facet variables
annotation_data <- data.frame(
  group1 = c("A", "B"),
  group2 = c("X", "Y"),
  label = c("Annotation for A-X", "Annotation for B-Y")
)

p + geom_text(data = annotation_data, aes(label = label), 
              x = Inf, y = Inf, hjust = 1.1, vjust = 1.5)
```


```{r raw_sweets}
# the raw data 
rawsweets <- META %>% 
  mutate(log_div = log(simpson_reciprocal)) %>% 
  mutate(antibiotics = if_else(empirical == 'FALSE', 'not exposed', 'exposed'),
         antibiotics = factor(antibiotics, levels = c('not exposed','exposed'))) %>% 
  ggscatter(x = 'fg_sweets', y = 'log_div', color = 'antibiotics',
            ylab = 'log(diversity)',xlab = 'Sweets consumed (grams)',
            alpha = 0.1, shape = 16, size = 1,
            add = "reg.line",  # Add regressin line
           add.params = list(color = 'antibiotics', fill = 'antibiotics', alpha = 0.3, size = 1.5), # Customize line
           conf.int = TRUE, # Add confidence interval
           cor.coef = TRUE, # Add correlation coefficient.
           cor.coeff.args = list(method = "spearman",  label.sep = "\n", cor.coef.name = c("rho"),p.accuracy = 0.01, r.accuracy = 0.01,label.x.npc = "left", label.y.npc = "bottom", size = 3.5)) +
  geom_text(data = num_annot, aes(label = lbl), 
              x = Inf, y = Inf, hjust = 1.1, vjust = 1.5) +
  #scale_x_sqrt() +
  scale_y_sqrt() +
  scale_fill_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  scale_colour_manual('antibiotics',values = palette, labels=c('not exposed', 'exposed')) +
  facet_wrap(~ antibiotics, labeller = 'label_both', dir = 'h') +
  theme(aspect.ratio = 1, 
        legend.position = 'none',
          strip.background = element_blank(),
        strip.text.x = element_blank(), 
     axis.text=element_text(size=9), axis.title=element_text(size=9)) 
rawsweets
```



```{r}
# for the legend
forlegend <- conditional %>%   
  ggplot() +
  geom_smooth(aes(x = effect1__, y = estimate__, ymin = lower__, ymax = upper__, fill = effect2__, color = effect2__),
              stat = "identity",
              alpha = .3, linewidth = 1.5)+ 
  scale_fill_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  scale_colour_manual('antibiotics', values = palette, labels=c('not exposed', 'exposed')) +
  facet_wrap(~ shortname, nrow = 3, scales = 'free_x') +
  ylim(0, 3.3) +
  labs(y = 'Predicted log(diversity)', x = 'Food group consumed (grams)') +
  theme_classic() +
  theme(legend.position = c(1,1), legend.title = element_text(size = 8, face="bold"),
        legend.text = element_text( size=8, face="bold"),
        #legend.background = element_rect(fill="white",size=0.2, linetype="solid"),
        legend.background=element_rect(fill = alpha("white", 0)),
       legend.key=element_rect(fill = alpha("white", 0)),
        aspect.ratio = 1, 
        strip.background = element_rect(color="white", fill=strip_color, size=1.5,linetype="solid"),
     axis.text=element_text(size=8), axis.title=element_text(size=axis_text_size))    +
  guides(fill = guide_legend(direction = "vertical"), color = guide_legend(direction = "vertical"))
```

# Final F2    

```{r}
title <- ggdraw() + 
  draw_label("Fig. 2",fontface = 'bold',
    x = 0,hjust = 0 ) +
  theme( plot.margin = margin(0, 0, 0, 5))

f2_top <-  plot_grid(f2a,diagram,macro_pt,
                     labels = c('A','B', 'C'),
                rel_widths = c(0.6,1.2, 0.6),
                 nrow = 1)

middle_right <-  plot_grid(macro_temporal,NA, rawsweets,
                labels = c('E',NA, 'F'),label_y = .8,
                rel_heights = c(1,0,.6),
                  ncol = 1) 

middle_row <- plot_grid(fg_temporal,middle_right,
                rel_widths = c(1,1),labels = c('D',NA),
                 nrow = 1)  

# the legend for the panels 3*3 
legend9 <- get_legend(forlegend)   

# combine the bottom left and the grid panels
f2_bottom <- condiall

f2 <- plot_grid(f2_top,middle_row, f2_bottom,
                rel_heights = c(.7,1.6, 1.7),
                align = 'hv',axis = 'lrtb',
                 ncol = 1)
   
combined <- plot_grid(
  title, f2,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
) +theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/F2_model_results_176.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', 
      #plot = combined, 
      dpi = 300)   
```


 