---
title: "New F4"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(scales)
library(tidybayes)
library(ggtext)
library(cowplot)
library(ggsci)
zero_line_size = .8
theme_set(theme_pubr(base_size = 10))
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
DTB <- read_csv('../data/152_combined_DTB.csv')
```

# spearman cor

```{r}
# correlate top genus abundance with diversity, check if entero and kleb have most negative correlation
set.seed(1)
meta <- read_csv('../data/153_combined_META.csv')
g_relab <- read_csv('../data/022_ALL173_stool_samples_genus_counts.csv') %>% 
  spread('genus','relab', fill = 0) %>% 
  gather('genus','relab', names(.)[2]:names(.)[ncol(.)]) %>% 
  inner_join(meta %>% select(sampleid, simpson_reciprocal)) %>% 
  mutate(pseudotiny = runif(nrow(.), min = 0, max = 10^-10) ) %>% 
  mutate(changed_relab = relab + pseudotiny)

# just calculate the spearman correlation and p value
spearman_res <- g_relab %>% 
  split(.$genus) %>% 
  imap_dfr(function(.x, .y ){
    # the spearman correlation 
      spearman_cor = cor.test(.x$simpson_reciprocal, .x$changed_relab, method = c( "spearman"), exact = T)
      return(list(genus = .y, rho = spearman_cor$estimate, pval = spearman_cor$p.value))
  } ) 

# the smallest nonzero p value 
pvals <- spearman_res %>% 
  filter(pval > 0) 
tinypseudo <- min(pvals$pval)/10

# show the % of the samples that have the relab of the genus > 10^-4
perc_thre <- g_relab %>% 
  count(genus, relab > 10^-4) %>% 
  filter(`relab > 10^-4` == 'TRUE') %>% 
  mutate(passthre_perc = round(n/1009*100, 0))

spearman_all <- spearman_res %>% 
  left_join(perc_thre) %>% 
  mutate(n = ifelse(is.na(n), 0, n),
         passthre_perc = ifelse(is.na(passthre_perc), 0, passthre_perc)) %>% 
    filter(passthre_perc > 10) %>% 
  mutate(padj = p.adjust(pval, method = 'BH')) %>% 
  mutate(sig05 = if_else(padj < 0.05, 'FDR < 0.05', 'FDR >= 0.05')) %>% 
  mutate(Correlation = if_else(rho >= 0, 'higher_div', 'lower_div')) %>% 
  arrange(rho, desc(genus)) 

res <- spearman_all %>% 
  mutate(Correlation = factor(Correlation, levels = c('lower_div','higher_div')))
```

# 4A: bar plot

```{r}
# make a panel with only top 5 significant ones in either direction for the main figure 3
main <- res %>% 
  filter(sig05 == 'FDR < 0.05') %>% 
  split(.$Correlation) %>% 
  map(function(df){
    df %>% mutate(absrho = abs(rho)) %>% slice_max(order_by =absrho, n = 5 )
  }) %>% bind_rows() %>% 
  arrange(desc(rho))

genus_order <- main$genus

correbar <- main %>% 
  mutate(genus = factor(genus, levels = genus_order)) %>% 
  ggplot( aes(x = genus, y = 0, xend = genus, yend = rho, color = Correlation)) + 
  geom_segment(size = 4) + 
  labs(x = '', y ='Spearman correlation') +
  scale_color_jco() +
  coord_flip() +
  theme(axis.text=element_text(size=10),axis.title=element_text(size=10),legend.position = 'none',
        axis.text.y = element_markdown(face = "italic"),
         aspect.ratio=1/1.3)
correbar
```

## supp: all bars 

```{r}
# make a panel with all the sig ones for the supplementary
# use the more abundant genus from the filtering I used
selected <- read_csv('../data/087_more_abundant_0.002_genus_33.csv')
 
selected_bars <- res %>% 
  filter(genus %in% selected$genus) %>% 
  filter(sig05 == 'FDR < 0.05') %>% 
  arrange(desc(rho))

all_order <- selected_bars$genus

correbar_all <- selected_bars %>% 
   mutate(genus = factor(genus, levels = all_order)) %>%
 ggplot( aes(x = genus, y = 0, xend = genus, yend = rho, color = Correlation)) + 
  geom_segment(size = 5) + 
  labs(x = '', y ='Spearman correlation') +
  scale_color_jco() +
  coord_flip() +
  theme(axis.text=element_text(size=10),axis.title=element_text(size=10),legend.position = 'none',
        axis.text.y = element_markdown(face = "italic"))

title <- ggdraw() + 
  draw_label(
    "Fig. S12",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )
 
combined <- plot_grid(
  title, correbar_all,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,5,8,2), "cm"))

ggsave('../results//S12_genus_diversity_correlation_178.pdf',
      width = 215.9, height = 279.4, units = "mm", device = 'pdf', plot = combined, dpi = 300)
```

# 4B: the Enterococcus results

```{r}
library(tidyverse)
library(cowplot)
library(broom.mixed)
library(brms)   
library(ggpubr)
library(tidybayes)
library(brmstools)
library(bayesplot)
library(gt)
library(rcompanion)
library(janitor)
library(ggtext)
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
```

```{r}
clr_res <- read_csv('../data/R29_all_ASV_CLR_counts.csv')

meta <- read_csv('../data/153_combined_META.csv') %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>%
  mutate(pid = factor(pid)) %>%
    # This divides all the new intake columns by 100.
  mutate(across(starts_with("fg_"), ~ .x / 100)) |> 
  full_join(clr_res |> select(sampleid, asv_1_clr = asv_1))

all_food_vars <- meta %>% select(starts_with('fg')) %>% colnames()

# Create the interaction terms for all food variables in this iteration
interaction_terms <- paste(all_food_vars, "empirical", sep = ":")

# Build the full formula string dynamically
formula_string <- paste(
  "asv_1_clr ~ 0 + intensity + empirical + TPN + EN  +",
  paste(interaction_terms, collapse = " + "),
  "+ (1 | pid) + (1 | timebin)"
)

# Convert the string to a formula object
formula <- brms::bf(as.formula(formula_string))

# Build the priors by adding them together.
# This single prior() call applies to all coefficients listed in `all_food_coefs`.
priors <-
    prior(normal(0, 1), class = 'b') + # General prior for all food effects
    # Specific priors that override the general one for non-food covariates
    prior(normal(0, 0.1), class = 'b', coef = "TPNTRUE") +
    prior(normal(0, 0.1), class = 'b', coef = "ENTRUE") +
    prior(normal(0, 0.5), class = 'b', coef = "empiricalTRUE") 

#Fit the model (using fewer iterations for this example to run quickly)
model_fit <- brm(
  formula = formula,
  data = meta,
  prior = priors,
    warmup = 1000, iter = 3000,
    chains = 4, cores = 4,
    seed = 123,
    silent = 2,
  control = list(adapt_delta = 0.99)
)

results_df <- tidy(model_fit, conf.int = TRUE) %>%
  mutate(conf.low = round(conf.low, 2),
         conf.high = round(conf.high, 2))
```
## forest figure 

```{r}
# the above figure but make it the way the other figure look like
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')

replacement_dictionary <- setNames(key$shortname, key$fg1_name)

level_order <- rev(c(
    "abx", "EN", "TPN", 
    "abx * Sweets", "Sweets",
    "abx * Grains", "Grains",
    "abx * Milk", "Milk",
    "abx * Eggs", "Eggs",
    "abx * Legumes", "Legumes",
    "abx * Meats", "Meats",
    "abx * Fruits", "Fruits",
    "abx * Oils", "Oils",
    "abx * Vegetables", "Vegetables"
))

cleaned_effects <- results_df %>%
  # Keep only the fixed effects
  filter(effect == "fixed") %>%
  # Create a new column to distinguish main effects from interactions
  mutate(
    effect_type = if_else(str_detect(term, ":"), "Interaction", "Main Effect"),
    # Create clean labels for plotting
    clean_term = term %>%
      str_replace("empiricalTRUE$", "abx") %>%
      str_remove_all("empiricalFALSE:|avg_intake_|TRUE$") %>%
      str_replace_all( replacement_dictionary) %>%
      str_replace("empiricalTRUE:", "abx * ") %>%
      str_replace_all("_", " ") 
  ) %>%
  filter(!str_detect(clean_term, 'intensity')) %>%
  # Create a new column to identify significant results
  # The condition is TRUE if conf.low and conf.high have the same sign (i.e., don't cross zero)
  mutate(is_significant = (conf.low * conf.high) > 0) %>%
  mutate(clean_term = factor(clean_term, levels = level_order))

shading_df <- cleaned_effects %>%
  mutate(y_numeric = as.numeric(clean_term)) %>%
  filter(str_detect(clean_term, "\\*")) # Filter for interaction terms

plot_asv1 <- ggplot(cleaned_effects, aes(x = estimate, y = clean_term)) +
  geom_rect(
    data = shading_df,
    aes(ymin = y_numeric - 0.5, ymax = y_numeric + 0.5, xmin = -Inf, xmax = Inf),
    fill = "#FBEADC", # A light orange/peach color like the example
    alpha = 0.7,
    inherit.aes = FALSE
   ) +
   # Add a vertical line at zero, which represents "no effect"
  geom_vline(xintercept = 0, linetype = "solid", color = "blue",size = 0.8) +
   # Use geom_pointrange to show the estimate (point) and confidence interval (line)
   geom_pointrange(
   aes(xmin = conf.low, xmax = conf.high, color = is_significant),
     size = 0.25,linewidth = 1,
  ) +
  scale_color_manual(
    values = c(
      "TRUE" = "red",
      "FALSE" = "black"
    ), name = "Effect Status" # Legend title
  ) +
  scale_y_discrete( labels = function(x) { ifelse(str_detect(x, '\\*'),  str_glue("<b style='color:royalblue'>{x}</b>"), as.character(x)) }) +
  # Add labels and a clean theme
  labs(
    x = "CLR(ASV 1) change",
    y = ''
  ) +
  theme_classic() +
  theme(legend.position = "none", axis.text.y = element_markdown(), axis.text=element_text(size=10),axis.title=element_text(size=10),
         aspect.ratio=1.3)

plot_asv1
```

# 4C: the mouse experiment   

```{r combined_data}
newest <- readxl::read_excel('../data/Sucrose_All Experiments Consolidated .xlsx') %>% 
  mutate(Log_CFUs_per_GramStool = log10((((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1) ) %>%   
  mutate(Day = if_else(Day == 0, 1, Day)) |> 
  separate(Treatment, into = c('diet_treatment','abx_treatment'), sep = ', ', remove = T) %>% 
  mutate(diet_treatment = if_else(diet_treatment == 'Vehicle','vehicle','sucrose'),
         abx_treatment = if_else(str_detect(abx_treatment, 'Bia'),'biapenem',abx_treatment),
         diet_treatment = factor(diet_treatment, levels = c('vehicle','sucrose')),
         abx_treatment = factor(abx_treatment, levels = c('PBS','biapenem'))) %>% 
  mutate(CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1) %>% 
  select(Experiment:Mouse_identifier, CFUs_per_GramStool, Log_CFUs_per_GramStool)

# are the mice paired in each of the treatment group

```

```{r}
# N-N mice per group; 2 independent experiments.  for the mouse experiments
n_per_grp <- newest %>% 
  count(diet_treatment, abx_treatment)
range(n_per_grp$n)
```



```{r}
# maybe I can plot in a different way 
plotdf <- newest %>% 
  #filter(Day != 3) %>% 
  mutate(Day = factor(Day)) %>% 
  arrange(abx_treatment,diet_treatment,  Day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{Day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  mutate(grp = factor(grp, levels = c('PBS__vehicle','PBS__sucrose','biapenem__vehicle','biapenem__sucrose')))
```


```{r trapezpid_auc}
# the trapezpid auc
dat_entero <- newest %>% 
  select(diet_treatment,
         abx_treatment,
         Day,
         Mouse_identifier,
         CFUs_per_GramStool)

dat_entero_wide <- dat_entero %>% 
  pivot_wider(id_cols = c(diet_treatment,
                          abx_treatment,
                          Mouse_identifier),
              names_from = Day,
              names_prefix = "Day",
              values_from = CFUs_per_GramStool)
 
dat_entero_wide <- dat_entero_wide %>% 
  mutate(trap_0_3 = (Day0  + Day3 )*3/2,
         trap_3_6 = (Day3  + Day6 )*3/2,
         trap = trap_0_3 + trap_3_6,
         groups = paste(abx_treatment,
                         diet_treatment,sep="__")) %>% 
  mutate(groups = factor(groups, levels = c('PBS__vehicle','PBS__sucrose','biapenem__vehicle','biapenem__sucrose')))

grps <- plotdf %>% count(xvar)

df <- dat_entero_wide %>% 
  filter(Day6 < Day0)
```

```{r}
# calculate the trapezoidal auc from the log 10 transformed value

library(DescTools) 

# Now, calculate the AUC for each mouse.
# We group by mouse ID and treatment, then summarize to get one AUC value per mouse.
auc_results <- newest %>%
  group_by(Mouse_identifier, diet_treatment, abx_treatment, Experiment ) %>%
  summarize(
    # The AUC function from DescTools calculates the area under the curve.
    # We use the log-transformed CFU values for this calculation.
    auc_value = AUC(x = Day, y = Log_CFUs_per_GramStool),
    # The .groups = 'drop' argument cleans up the grouping structure afterward.
    .groups = 'drop'
  ) |> 
  mutate(groups = paste(abx_treatment, diet_treatment,sep="__"),
         groups = factor(groups, levels = c('PBS__vehicle','PBS__sucrose','biapenem__vehicle','biapenem__sucrose')))

# the boxplot of the AUC
my_comparisons <- list( c("PBS__vehicle", "biapenem__vehicle"), 
                        c("biapenem__vehicle", "biapenem__sucrose"), 
                        c("PBS__vehicle", "PBS__sucrose"))

f3_AUC_log10 <- ggboxplot(auc_results,
          x="groups",add = 'jitter',
          y="auc_value", color  = 'groups', add.params = list(alpha = 0.5, shape = 16)) +
  ylab("Trapezoidal\nAUC")+xlab('') +
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  #scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  stat_compare_means(comparisons = my_comparisons,label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  theme(axis.title=element_text(size=10), 
        axis.text =  element_text(size = 10),
        #axis.text.x = element_blank(),
        legend.position = 'none',aspect.ratio=1/3.1, axis.ticks.x = element_blank())

f3_AUC_log10
```

## fold_change

```{r fold_change}
# the median fold change and the p value for the star in the 3C upper panel
deltas <- plotdf %>%
  select(grp, Day, Mouse_identifier, CFUs_per_GramStool) 

# the fold change on day 3
# calculate the fold change between the median of the two groups on day 3 and day 6 respectively
mediancfu <- deltas %>% filter(str_detect(grp, 'biapenem')) %>% droplevels() %>% 
  split(list(.$grp, .$Day)) %>% 
  map(function(df){
    return(summarise(.data = df, median_cfu = median(CFUs_per_GramStool)) %>% pull(median_cfu)) 
  }) %>% bind_rows(.id = 'grps') %>% 
  gather('grps','median_cfu')

# fc for day 3
round( (mediancfu %>% filter(grps == 'biapenem__sucrose.3') %>% pull(median_cfu)) / mediancfu %>% filter(grps == 'biapenem__vehicle.3') %>% pull(median_cfu),2)

# fc for day 6
round( (mediancfu %>% filter(grps == 'biapenem__sucrose.6') %>% pull(median_cfu)) / mediancfu %>% filter(grps == 'biapenem__vehicle.6') %>% pull(median_cfu),2)
```


```{r p_values}
# calculate the p values
deltas %>% 
  filter(str_detect(grp, 'biapenem') & Day != '0') %>% 
  droplevels() %>% 
  split(.$Day) %>% 
  map(function(df){
    res = wilcox.test(CFUs_per_GramStool ~ grp, data = df,
                   exact = FALSE)
    return(res$p.value)
  })
```


```{r p_values}
res <- wilcox.test(d3 ~ grp, data = deltas %>% 
  filter(str_detect(grp, 'biapenem')) %>% 
  select(grp, Mouse_identifier, d3),
                   exact = FALSE)
res


res <- wilcox.test(d6 ~ grp, data = deltas %>% 
  filter(str_detect(grp, 'biapenem')) %>% 
  select(grp, Mouse_identifier, d6),
                   exact = FALSE)
res
```

## mouse panel

```{r}
f3_days <- plotdf %>%    
  ggboxplot(x = 'xvar', y = 'CFUs_per_GramStool',add = 'jitter', 
             xlab = '', ylab = 'Enterococcal\n CFU/gram',, add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  stat_compare_means(comparisons = list(c('biapenem__vehicle__3','biapenem__sucrose__3'), c('biapenem__vehicle__6','biapenem__sucrose__6')),label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:12)),  labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(labels=rep(c(0,3,6),4)) + 
  theme(axis.text =  element_text(size = 10),axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/1.3)

# the boxplot of the AUC
my_comparisons <- list( c("PBS__vehicle", "biapenem__vehicle"), 
                        c("biapenem__vehicle", "biapenem__sucrose"), 
                        c("PBS__vehicle", "PBS__sucrose"))

f3_AUC <- ggboxplot(dat_entero_wide,
          x="groups",add = 'jitter',
          y="trap", color  = 'groups', add.params = list(alpha = 0.5, shape = 16)) +
  ylab("Trapezoidal\nAUC")+xlab('') +
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  stat_compare_means(comparisons = my_comparisons,label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  theme(axis.text.x = element_blank(),axis.title=element_text(size=10), axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/3.1, axis.ticks.x = element_blank())

# combine the above two together on a stack
f3_mouse <- plot_grid(f3_days,NA, f3_AUC,  ncol = 1,
                align = 'vh', axis = 'lrtb', rel_heights = c(1.1,-0.2,0.7))
f3_mouse


f3_AUC_stats <- ggboxplot(dat_entero_wide,
          x="groups",add = 'jitter',
          y="trap", color  = 'groups') +
  ylab("Trapezoidal\nAUC")+xlab('') +
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  stat_compare_means(comparisons = my_comparisons, method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +  
  theme(axis.text.x = element_blank(),axis.title=element_text(size=10), axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/3.1, axis.ticks.x = element_blank())
```

# final graph

```{r}
# assemble
title <- ggdraw() + 
  draw_label(
    "Fig. 4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )


f3 <- plot_grid(correbar, plot_asv1,f3_days, f3_AUC, label_size = 12, ncol = 1,labels = c('A','B','C', NA),
                align = 'vh', axis = 'lrtb', rel_heights = c(1,1.55,1, 0.55))

 
combined <- plot_grid(
  title, f3,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,9,2,1), "cm"))

# ggsave('../results/F4_current_178_changing.pdf',
#       width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)

ggsave('../data/178_F4_current_new.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)
```

```{r}
# the figure for the rebuttal that docmnets the time course of the abx + sugar group
sub <- newest %>% filter(diet_treatment == 'sucrose' & abx_treatment == 'biapenem')

# find the three mice that are very low on the last day 
three <- sub %>% filter(Day == 6) %>% 
  slice_min(order_by = Log_CFUs_per_GramStool, n = 3) %>% pull(Mouse_identifier)

sub %>% 
  mutate(Mouse = if_else(Mouse_identifier %in% three, T, F)) %>% 
  ggboxplot(x = 'Day', y = 'Log_CFUs_per_GramStool',
            xlab = 'Day', ylab = 'Enterococcal CFU/gram\nlog10 transformed', title = 'biapenem + sucrose group') +
   geom_line( aes(group = Mouse_identifier, color = Mouse)) +
  scale_color_manual(values = c('gray','red'), label = c('Other','Particularly low on day 6'))+
  theme(legend.position = "right") 
ggsave('../data/178_low_three.pdf', width = 6, height = 3)
```

