---
title: "GVHD experiment mice sequencing 16s"
output: html_document
date: "2024-07-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(scales)
library(ggpubr)
library(janitor)
library(Maaslin2)
library(vegan)
library(vdbR)
connect_database('~/dbConfig.txt')
```
```{r}
gvhdall <- read_csv('../data/204_mice_diet_gvhd_all.csv') %>% 
  rename(day_relative_to_transplant = day)

meta <- gvhdall %>%
  select(-Taxon, -relab) %>% 
  distinct() 
```

```{r}
# there is a discrepancy of enterococcus bloom in counts data on day 4 in abx +vehicle in BMT mice but not so in 16s data 
gvhd_counts <- readxl::read_excel('../data/BMT2_Metadata_ForCSVImport copy.xlsx') %>% 
  mutate(Log_CFUs_per_GramStool = log10((((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1) ) %>%   
  mutate(CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1) %>% 
  clean_names() %>% 
  separate_rows(treatment, sep = "\\+") %>% 
  mutate(grp = case_when(
    str_detect(treatment, '^BM') ~ 'gvhd_grp',
    str_detect(treatment, 'B|PBS') ~ 'abx_treatment',
    str_detect(treatment, 'PH|S') ~ 'diet_treatment'
  )) %>% 
  spread('grp','treatment') %>% 
  mutate(diet_treatment = if_else(diet_treatment == 'PH','vehicle','sucrose'),
         abx_treatment = if_else(str_detect(abx_treatment, '^B'),'biapenem',abx_treatment),
         gvhd_grp = if_else(str_detect(gvhd_grp, '^BMT'),'BM+Tcells','BMonly')) %>% 
  rename(tube_no = tube_id) %>% 
  left_join(gvhdall %>% distinct(tube_no, sampleid))
```
 
# transplant_CFU_plot    

```{r}
# only include the CFU of the BM only and BMT results, since the day 4 of the abx + vehicle looks weird
# also include the day 9 of the CFU data
transplant_CFU <- gvhd_counts %>% 
    select( day_relative_to_transplant, cf_us_per_gram_stool,abx_treatment:gvhd_grp) %>% 
  filter(!is.na(cf_us_per_gram_stool)) %>% 
  arrange(gvhd_grp, abx_treatment,desc(diet_treatment),  day_relative_to_transplant) %>% 
  mutate(xvar = str_glue('{gvhd_grp}__{abx_treatment}__{diet_treatment}__{day_relative_to_transplant}')) %>% 
  mutate(grp = str_glue('{gvhd_grp}__{abx_treatment}__{diet_treatment}')) %>% 
  mutate(grp = factor(grp, levels = c('BM+Tcells__PBS__vehicle','BM+Tcells__PBS__sucrose','BM+Tcells__biapenem__vehicle','BM+Tcells__biapenem__sucrose','BMonly__PBS__vehicle','BMonly__PBS__sucrose','BMonly__biapenem__vehicle','BMonly__biapenem__sucrose')))

transplant_CFU_plot <- transplant_CFU %>% 
  filter(gvhd_grp == 'BMonly') %>% 
  ggboxplot(x = 'xvar', y = 'cf_us_per_gram_stool',add = 'jitter', 
             xlab = '', ylab = 'Enterococcal\n CFU/gram', add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp') +
  scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2', 'gray76','#ffbcdc','gray32','deeppink2'))+
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  stat_compare_means(comparisons = list(
    #c('BMonly__PBS__vehicle__0','BMonly__PBS__vehicle__9'),
    c('BMonly__PBS__vehicle__4','BMonly__PBS__sucrose__4'), 
    c('BMonly__PBS__vehicle__4','BMonly__biapenem__vehicle__4'),
    c('BMonly__biapenem__vehicle__6','BMonly__biapenem__sucrose__6'),
     c('BMonly__biapenem__vehicle__9','BMonly__biapenem__sucrose__9')
    ),
    label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T, step.increase = 0.2) +
  theme_light() +
  scale_x_discrete(labels=c(0,4,6,9,0,4,6,0,4,6,9,0,4,6,9,0,4,6,9,0,4,6,9,0,4,6,9,0,4,6,9)) + 
  theme(axis.text.x =  element_text(size = 10),axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/2.8)
transplant_CFU_plot
transplant_CFU_plot %>% write_rds('../data/02_transplant_CFU_plot.RDS')

transplant_CFU %>% 
  count(abx_treatment, diet_treatment, day_relative_to_transplant, gvhd_grp) %>% 
  filter(gvhd_grp == 'BMonly') %>% 
  summarise(min_ = min(n), max_ = max(n))
  
```


```{r}
# to make them three different columns and do a pairwise correlation
threecols <- two %>% 
  spread('type','value') %>% 
  mutate(day_relative_to_transplant = factor(day_relative_to_transplant))
```

