---
title: "Split out oral nutritional supplements"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
--- 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(brms)   
library(tidybayes)
library(cowplot)
library(brmstools)
library(ochRe)
library(bayesplot)
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
theme_set(theme_tidybayes() + panel_border())
ncores <- parallel::detectCores()
key <- read_csv('../data/food_group_color_key_final.csv', col_types = 'ccccc')
axis_text_size <- 10
axis_title_size <- 10
```

```{r}
dtb <- read_csv('../data/152_combined_DTB.csv') %>% 
  mutate(Food_code = as.character(Food_code))

g9 <- dtb %>% 
  filter(str_detect(Food_code, '^9')) %>% 
  distinct(Food_code, description)
```


# Split out EN + nutritional drink/shake/powermix into a separate group 

```{r}
nutritional_codes <- g9 %>% 
  filter(str_detect(description, 'Nutritional|ONS formula')) %>% 
  pull(Food_code)
```


```{r}
dtb_ONS <- dtb %>% 
  mutate(Food_code = if_else(Food_code %in% nutritional_codes, 
                             str_replace(Food_code, '^9','N'),
                             Food_code)) 

fgrps_df <- dtb_ONS %>% 
  select(pid, fdrt, dehydrated_weight, Food_code) %>% 
  mutate(fgrp1 = str_sub(Food_code, 1, 1))

total_per_group <- fgrps_df %>% 
  group_by(pid, fdrt, fgrp1) %>% 
  summarise(grp_tol = sum(dehydrated_weight)) %>% 
  mutate(fg1_name = case_when(
    fgrp1 == '1' ~ 'fg_milk',
    fgrp1 == '2' ~ 'fg_meat',
    fgrp1 == '3' ~ 'fg_egg',
    fgrp1 == '4' ~ 'fg_legume',
    fgrp1 == '5' ~ 'fg_grain',
    fgrp1 == '6' ~ 'fg_fruit',
    fgrp1 == '7' ~ 'fg_veggie',
    fgrp1 == '8' ~ 'fg_oils', 
    fgrp1 == '9' ~ 'fg_sweets',
    fgrp1 == 'N' ~ 'fg_ONS'
  ))
```
```{r}
meta <- read_csv('../data/153_combined_META.csv')

stb_pair <- meta %>%  
  select(pid, sdrt) %>% 
  transmute(pid = pid,
            p1d = sdrt-1,
            p2d = sdrt-2) 

mean_p2d_diet <-  function(pid_, p1d_, p2d_){
  df = total_per_group %>% 
    filter(pid == pid_) %>% 
    filter(fdrt %in% c(p1d_, p2d_  )) %>% 
    group_by(fg1_name) %>% 
    summarise(ave_fg = sum(grp_tol)/2)
  return(df)
}

mean_p2d_df <- pmap(stb_pair, function(pid, p1d, p2d){
    mean_p2d_diet(pid, p1d, p2d)
  }) %>% 
  set_names(meta %>% pull(sampleid)) %>% 
  bind_rows(.id = 'sampleid') %>% 
  spread(key = 'fg1_name', value = 'ave_fg', fill = 0) %>% 
  inner_join(meta %>% 
               select(-starts_with('fg')), by = "sampleid") %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left'))
```


```{r}
meta_ONS <- mean_p2d_df %>% 
  mutate(timebin = cut_width(sdrt, 7, boundary=0, closed = 'left')) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(pid = factor(pid))  %>% 
  mutate(fg_egg = fg_egg/100,
         fg_fruit = fg_fruit/100,
         fg_grain = fg_grain/100,
         fg_legume = fg_legume/100,
         fg_meat = fg_meat/100,
         fg_milk = fg_milk/100,
         fg_oils = fg_oils/100,
         fg_sweets = fg_sweets/100,
         fg_veggie = fg_veggie/100,
         fg_ONS = fg_ONS/100) %>% 
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(      fg_fruit_e= fg_fruit*abx,  
                fg_meat_e=fg_meat*abx,
                fg_milk_e=fg_milk*abx,
                fg_oils_e=fg_oils*abx,
                fg_egg_e=fg_egg*abx,
                fg_grain_e=fg_grain*abx,
                fg_sweets_e=fg_sweets*abx,
                fg_legume_e=fg_legume*abx,
                fg_veggie_e = fg_veggie*abx,
              fg_ONS_e = fg_ONS*abx)
```

# run the updated model

```{r}  
# spent 1-1.5 hours and finally realized I set my code that way for a reason ......
mod_ONS <-  log(simpson_reciprocal) ~ 0 +
                intensity+
               fg_fruit_e+
                fg_meat_e+
                fg_milk_e+
                fg_oils_e+
                fg_egg_e+
                fg_grain_e+
                fg_sweets_e+
                fg_legume_e+
                fg_veggie_e+
                fg_ONS_e+
                abx+
               fg_fruit+
                fg_meat+
                fg_milk+
                fg_oils+
                fg_egg+
                fg_grain+
                fg_sweets+
                fg_legume+
                fg_veggie+
                fg_ONS+
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)

get_prior(mod_ONS,data = meta_ONS )

div_priors_ONS <- c(# for the food group variables
            prior(normal(0, 1), class = 'b', coef = "fg_egg"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie"),
             prior(normal(0, 1), class = 'b', coef = "fg_ONS"),
            # interaction terms
            prior(normal(0, 1), class = 'b', coef = "fg_egg_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_fruit_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_grain_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_legume_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_meat_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_milk_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_oils_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_sweets_e"),
            prior(normal(0, 1), class = 'b', coef = "fg_veggie_e"),
             prior(normal(0, 1), class = 'b', coef = "fg_ONS_e"),
            # for the TPN
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical
            prior(normal(0, 0.5), class = 'b', coef = "abx"),
            # for the intensity
            prior(normal( 2, .1), class = 'b', coef = "intensityablative"),
            prior(normal( 2, .1), class = 'b', coef = "intensityreduced"),
            prior(normal( 2, .1), class = 'b', coef = "intensitynonablative")
            )

model_div_ONS <- brm( mod_ONS,  
              data = meta_ONS, 
              warmup = 1000, iter = 3000, 
              prior = div_priors_ONS,
              cores = ncores, 
              chains = 2, 
               control = list(adapt_delta = 0.99),
              seed = 123, sample_prior = T, file = '../data/R03_interaction_conditional_model_ONS')

as_draws_df(model_div_ONS) %>% write_csv('../data/R03_interaction_conditional_model_ONS.csv')
```

# visualize the results

```{r}
# to produce the highest density plot and the conditional plot 
# the matchingtb needs to be adjusted for the additional ONS group

fg_order <- c( 'Vegetables','abx * Vegetables',
                 'Oils','abx * Oils',
                 'Fruits','abx * Fruits',
                 'Meats','abx * Meats',
                 'Legumes','abx * Legumes',
                 'Eggs','abx * Eggs',
                 'Milk','abx * Milk',
                 'Grains','abx * Grains',
                 'Sweets','abx * Sweets',
               'ONS','abx * ONS',
                 "TPN" ,"EN" , 'abx')


matchingtb <- read_rds('../data/196_matching_shortname.rds') %>% 
  mutate(shortname = as.character(shortname)) %>% 
  select(-ymin, -ymax) %>% 
  add_row(item = 'b_fg_ONS_e', shortname = 'abx * ONS', grp = 'temporal', xmin = -Inf, xmax = Inf, fill_ = 'interaction_fill') %>% 
  add_row(item = 'b_fg_ONS', shortname = 'ONS', grp = 'temporal', xmin = -Inf, xmax = Inf, fill_ = 'blue_fill') %>% 
  mutate(shortname = factor(shortname, levels = fg_order)) %>% 
  mutate(id = as.numeric(shortname)) %>% 
  mutate(ymin = id - 0.5,
         ymax = id + 0.5) 

fg <- read_csv('../data/R03_interaction_conditional_model_ONS.csv') %>% 
  select(starts_with('b_')) %>% 
  gather('item', 'coeff') %>% 
  inner_join(matchingtb)
```

```{r}
# cross0 <- fg %>%
#    filter(grp == 'temporal') %>% 
#   group_by(item) %>% 
#   summarise(q2.5 = quantile(coeff, probs = 0.025),
#             q97.5 = quantile(coeff, probs = 0.975)) %>% 
#   mutate(Cross = if_else(q2.5 >= 0 | q97.5 <= 0, F, T))

post_ONS <- fg %>% 
  filter(grp == 'temporal') %>% 
  left_join(cross0) %>% 
  ggplot() +
 stat_interval(aes(x = coeff, y = shortname),.width = c(.66, .95), fatten_point = 1.2) +
  scale_color_brewer(palette = 'RdPu', name = 'CI level') +
  geom_rect(data = matchingtb, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = fill_), alpha = .2) +
  scale_fill_manual(values=c("interaction_fill" = "lightblue", "blue_fill" = "royalblue")) +
  geom_vline(xintercept = 0, col = 'blue', linetype = 'twodash', size = 1) +
  labs(x = 'ln(diversity) change', y = '') +
  theme_classic() +
  scale_color_manual(values = c( "#d89060", "#a84830")) +
  guides(fill = "none") +
  theme(axis.text = element_text( size = 10),
        plot.background = element_rect(fill='transparent', color=NA), legend.position = 'none',
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)

post_ONS
```


