---
title: "Egg experiments in mice"
output: html_document
date: "2024-07-26"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(cowplot)
```

```{r}
# df <- readxl::read_excel('/Volumes/peledlab/Projects/2022_Diet Experiments/Antibiotics + Diet Murine Exhuastive Experiments_ 992022_For_review_V01.xlsx') %>% 
#   filter(Treatment %in% c('Egg, Biapenem','Egg, Vehicle','Plain Hydrogel, Biapenam','Plain Hydrogel, Vehicle')) 
# df %>% write_csv('../data/R04_egg_diet_experiments.csv')

egg <- read_csv('../data/R04_egg_diet_experiments.csv') %>% 
  filter(Day != 7) %>% 
  mutate(Dilution_factor = as.numeric(Dilution_factor),
         Colonies_counted = as.numeric(Colonies_counted)) %>% 
  mutate(Log_CFUs_per_GramStool = log10((((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/(Stool_weight_g * 1000))+1) ) %>%   filter(!is.na(Dilution_factor)) %>% 
  separate(Treatment, into = c('diet_treatment','abx_treatment'), sep = ', ', remove = T) %>% 
  mutate(diet_treatment = if_else(diet_treatment == 'Plain Hydrogel','vehicle','Egg'),
         abx_treatment = if_else(str_detect(abx_treatment, 'Bia'),'biapenem', "DPBS"),
         diet_treatment = factor(diet_treatment, levels = c('vehicle','Egg')),
         abx_treatment = factor(abx_treatment, levels = c('DPBS','biapenem'))) %>% 
  mutate(CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/(Stool_weight_g * 1000))+1) %>% 
  select(Experiment:Mouse_identifier, CFUs_per_GramStool, Log_CFUs_per_GramStool) %>% 
  mutate(Day = factor(Day)) %>% 
  arrange(abx_treatment,diet_treatment,  Day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{Day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  mutate(grp = factor(grp, levels = c('DPBS__vehicle','DPBS__Egg','biapenem__vehicle','biapenem__Egg')))

```

```{r}
library(scales)
egg_days <- egg %>%    
  ggboxplot(x = 'xvar', y = 'CFUs_per_GramStool',add = 'jitter', xlab = '', 
            ylab = 'Enterococcal\n CFU/gram',, add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('gray76','tan','gray32','tan4')) +
  stat_compare_means(comparisons = list(c('biapenem__vehicle__3','DPBS__vehicle__3'), c('biapenem__vehicle__3','biapenem__Egg__3')),label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:12)),  labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(labels=rep(c(0,3,6,9),4)) + 
  theme(axis.text =  element_text(size = 10),
        axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/1.3)
egg_days

```


```{r}
title <- ggdraw() + 
  draw_label(
    "Fig. R1",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0)
  )

plot_egg <- plot_grid(egg_days, nrow = 1)

 
combined <- plot_grid(
  title, plot_egg,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,5,1), "cm"))

ggsave('../data/Fig_R1_egg_days_04.pdf',
      width = 210, height = 157, units = "mm", device = 'pdf', plot = combined, dpi = 300) 
```

