---
title: "The fructose data"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(readxl)
library(janitor)
library(scales)
```

# the new mice data: three different kinds of sugars 

The tube weight need to be adjusted.    

```{r}
# three <- read_excel('/Volumes/peledlab/Projects/2024_Angel Rebuttal Exp /Healthy mice Biapenem_Diet_Exp/Angel Rebuttal_Exp2_Healthy mice Diet_Fructose_Sucrose_Glucose_v2.xlsx') %>% 
#   mutate(CFUs_per_GramStool = (((((Colonies_counted*(100/Plated_volume_ul))/100)/(10^Dilution_factor) )*1000)/Stool_weight_mg)+1)  %>% 
#   clean_names() %>% 
#   separate(treatment, into = c('abx_treatment', 'diet_treatment'), sep = '\\+', remove = T) %>% 
#   mutate(diet_treatment = if_else(diet_treatment == 'F','fructose',if_else(diet_treatment == 'G','glucose', if_else(diet_treatment == 'PH','vehicle', 'sucrose'))),
#          abx_treatment = if_else(abx_treatment == 'B','biapenem','DPBS'),
#          #diet_treatment = factor(diet_treatment, levels = c('vehicle','sucrose', 'fructose', 'glucose')),
#          abx_treatment = factor(abx_treatment, levels = c('DPBS','biapenem'))) 
# three %>% write_rds('../data/05_cleaned_three_sugars_longtime_mice.RDS')  

three <- read_rds('../data/05_cleaned_three_sugars_longtime_mice.RDS')
  
three %>% count(abx_treatment, diet_treatment) 

plotdf <- three %>% 
  mutate(day = factor(day)) %>% 
  arrange(abx_treatment,diet_treatment,  day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  mutate(grp = factor(grp, levels = c('DPBS__vehicle','DPBS__sucrose','DPBS__glucose','DPBS__fructose','biapenem__vehicle','biapenem__sucrose','biapenem__glucose','biapenem__fructose')))

plotdf %>% count(xvar)
```
# long time

```{r}
# plot 1 : the f3 setting but extend to day 9,14,21
f3_five <- three %>% 
  mutate(day = factor(day)) %>% 
  arrange(abx_treatment,desc(diet_treatment),  day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  filter(diet_treatment != 'fructose' & diet_treatment != 'glucose' ) %>% 
  mutate(grp = factor(grp, levels = c('DPBS__vehicle','DPBS__sucrose','biapenem__vehicle','biapenem__sucrose'))) 

f3_five_days <- f3_five %>%    
  ggboxplot(x = 'xvar', y = 'cf_us_per_gram_stool',add = 'jitter', 
             xlab = '', ylab = 'Enterococcal\n CFU/gram',, add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  stat_compare_means(comparisons = list(
    c('biapenem__vehicle__3','biapenem__sucrose__3'), 
    c('biapenem__vehicle__6','biapenem__sucrose__6'),
    c('biapenem__vehicle__9','biapenem__sucrose__9'),
  c('biapenem__vehicle__14','biapenem__sucrose__14'),
  c('biapenem__vehicle__21','biapenem__sucrose__21'),
   c('biapenem__vehicle__3','DPBS__vehicle__3'), 
    c('biapenem__vehicle__6','DPBS__vehicle__6'),
    c('biapenem__vehicle__9','DPBS__vehicle__9'),
  c('biapenem__vehicle__14','DPBS__vehicle__14'),
  c('biapenem__vehicle__21','DPBS__vehicle__21')
  ),
    label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T, step.increase = 0.2, label.size = 1) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(labels=rep(c(0,3,6,9,14,21),4)) + 
  theme_light() +
  theme(axis.text =  element_text(size = 10),axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/3)
f3_five_days %>% write_rds('../data/05_f3_five_days.RDS')
f3_five_days

f3_five %>% 
  count(experiment, abx_treatment,  diet_treatment , day) %>% 
  summarise(min_ = min(n), max_ = max(n))
```


# three sugars

```{r}
# plot 2: three total sugars but only day 0,3,6
f3_sugars <- three %>% 
  arrange(abx_treatment,desc(diet_treatment),  day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  filter(!day %in% c(9,14,21) ) %>% 
  mutate(grp = factor(grp, levels = c('DPBS__vehicle','DPBS__sucrose','DPBS__glucose','DPBS__fructose','biapenem__vehicle','biapenem__sucrose','biapenem__glucose','biapenem__fructose'))) 

f3_sugars %>% count(grp)


f3_sugars_days <- f3_sugars %>%    
  # remove three mice that have NA in the cfu counts cuz "mouse died extensive diarrhea"
  filter(!is.na(cf_us_per_gram_stool)) %>% 
  ggboxplot(x = 'xvar', y = 'cf_us_per_gram_stool',add = 'jitter', 
             xlab = '', ylab = 'Enterococcal\n CFU/gram',, add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('gray76','#ffbcdc','burlywood2','palegreen2','gray32','deeppink2','burlywood4','palegreen4')) +
  stat_compare_means(comparisons = list(
    c('biapenem__vehicle__3','biapenem__sucrose__3'), 
    c('biapenem__vehicle__6','biapenem__sucrose__6'),
    c('biapenem__vehicle__3','biapenem__glucose__3'), 
    c('biapenem__vehicle__6','biapenem__glucose__6'),
    c('biapenem__vehicle__3','biapenem__fructose__3'), 
    c('biapenem__vehicle__6','biapenem__fructose__6')
    
    ),
    label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T, step.increase = 0.2) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(labels=rep(c(0,3,6),8)) + 
  theme_light() +
  theme(axis.text =  element_text(size = 10),axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/3)
f3_sugars_days
f3_sugars_days %>% write_rds('../data/05_f3_sugars_days.RDS')
```

```{r}
# the median fold change and the p value for the star in the above figure on day 3
deltas <- f3_sugars %>%
  mutate(grp = str_glue('{abx_treatment}_{diet_treatment}')) %>% 
  select(grp, day, mouse_identifier, cf_us_per_gram_stool) %>% 
  spread('day','cf_us_per_gram_stool') %>%
  rename(d0 = `0`, d3 = `3`,d6 = `6`) %>%
  # remove any rows that has NA in D3
  filter(!is.na(d3))

# the fold change on day 3 between the two groups 
# should be computed as : median of the day3 of the abx only , and median of the day 3 of the abx + sugar , and the fold change of the two medians 
 
medians <- deltas %>% 
  split(.$grp) %>% 
  map(function(df){
    df %>% summarise(median_d3 = median(d3, na.rm = T),
                     median_d6 = median(d6, na.rm = T))
  }) %>% 
  bind_rows(.id = 'grp')
```


```{r}
# so the fold change between abx + sucrose and abx only on day 3 is : 
round(6.980520e+06	/1.672251e+05	, 1 )

# the above at day 6
round(17668.8445		/681.8511	, 1 )

# fructose 
round(9.411766e+06		/1.672251e+05	, 1 )

# glucose 
round(1.188999e+07		/1.672251e+05	, 1 )
```


```{r fc_fructose}
median(day3fc$fc_fructose)

res_fructose <- wilcox.test(d3 ~ grp, data = deltas %>% 
  filter(grp %in% c('biapenem_fructose','biapenem_vehicle')) %>% 
  select(grp, mouse_identifier, d3),
                   exact = FALSE)
res_fructose
```

```{r fc_glucose}
median(day3fc$fc_glucose, na.rm = T)

res_glucose <- wilcox.test(d3 ~ grp, data = deltas %>% 
  filter(grp %in% c('biapenem_glucose','biapenem_vehicle')) %>% 
  select(grp, mouse_identifier, d3),
                   exact = FALSE)
res_glucose
```
```{r sucrose_day3}
median(day3fc$fc_sucrose)

res_sucrose <- wilcox.test(d3 ~ grp, data = deltas %>% 
  filter(grp %in% c('biapenem_sucrose','biapenem_vehicle')) %>% 
  select(grp, mouse_identifier, d3),
                   exact = FALSE)
res_sucrose
```
```{r sucrose_day6}
day6fc <- deltas %>% 
  filter(str_detect(grp, 'biapenem')) %>% 
  select(grp, mouse_identifier, d6) %>% 
  spread('grp','d6') %>% 
  filter(!is.na(biapenem_vehicle)) %>% 
  mutate(fc_sucrose = round(biapenem_sucrose/biapenem_vehicle, 2)) 

median(day6fc$fc_sucrose)

res_sucrose_d6 <- wilcox.test(d6 ~ grp, data = deltas %>% 
  filter(grp %in% c('biapenem_sucrose','biapenem_vehicle')) %>% 
  select(grp, mouse_identifier, d6),
                   exact = FALSE)
res_sucrose_d6
```

