---
title: "No fiber diet CFU counts"
output: html_document
date: "2024-08-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(readxl)
library(janitor)
library(scales)
library(ggrepel)
library(cowplot)
library(kableExtra)
```

B+S  (Biapenem + Sucrose) PS (PBS + Sucrose) BP (Biapenem +Plain Hydrogel) and PP (PBS + Plain Hydrogel)

```{r}
# nofiber <- read_excel('../../MSS_pipeline-/scripts/food_tree/data/Angel Rebuttal_Exp2.xlsx') %>% 
#   clean_names() %>% 
#   filter(experiment == 2) %>% 
#   select(-tube_label, -date,-x14)
# nofiber %>% write_csv('../data/R07_no_fiber_experiment_data_CFU.csv')

nofiber <- read_csv('../data/R07_no_fiber_experiment_data_CFU.csv') %>% 
  mutate(CFUs_per_GramStool = (((((colonies_counted*(100/plated_volume_ul))/100)/(10^dilution_factor) )*1000)/stool_weight_mg)) %>% 
  mutate(treatment = str_replace(treatment, '\\d$',''),
         abx_treatment = if_else(str_detect(treatment, '^B'), 'biapenem','DPBS') ,
         diet_treatment = if_else(str_detect(treatment, 'S$'), 'sucrose', 'vehicle'),
         diet_treatment = factor(diet_treatment, levels = c('vehicle','sucrose')),
         abx_treatment = factor(abx_treatment, levels = c('DPBS','biapenem'))) %>% 
  select(experiment:treatment, CFUs_per_GramStool:diet_treatment) %>% 
  mutate(logcfu = log10(CFUs_per_GramStool)) 
#nofiber %>% distinct(treatment, abx_treatment, diet_treatment)
nofiber %>% distinct(day)
nofiber %>% write_csv('../data/07_nofiber.csv')

plotdf <- nofiber %>% 
  mutate(day = factor(day)) %>% 
  arrange(abx_treatment,diet_treatment,  day) %>% 
  mutate(xvar = str_glue('{abx_treatment}__{diet_treatment}__{day}')) %>% 
  mutate(grp = str_glue('{abx_treatment}__{diet_treatment}')) %>% 
  mutate(grp = factor(grp, levels = c('DPBS__vehicle','DPBS__sucrose','biapenem__vehicle','biapenem__sucrose')))

nofiber %>% 
  count(experiment, treatment, day) %>% 
  summarise(min_ = min(n), max_ = max(n))
```

```{r}
# test if the logcfu follow normality
nofiber %>% 
  split(list(.$day, .$abx_treatment, .$diet_treatment)) %>% 
  map(function(df){
    shapiro.test(x = df$logcfu)
  })
```

# nofiber days

```{r} 
nofiber_days <- plotdf %>%    
  ggboxplot(x = 'xvar', y = 'logcfu',add = 'jitter', xlab = '', 
            ylab = 'Enterococcal\n CFU/gram log10 transformed',, add.params = list(alpha = 0.5, shape = 16),
            width = 0.6,color  = 'grp')+
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  stat_compare_means(comparisons = list(  c('biapenem__vehicle__9','biapenem__sucrose__9')),
                     label= "p.signif", 
                     method= 't.test',tip.length = 0.015,exact=T,correct=T, step.increase = 0.1) +
  #scale_y_log10(breaks = c(1 %o% 10^(-1:12)),  labels = trans_format("log10", math_format(10^.x))) +
  scale_x_discrete(labels=rep(c(0,3,6,9),4)) + 
  theme_light() +
  theme(axis.text.x =  element_text(size = 10),
        axis.title=element_text(size=10),legend.position = 'none',aspect.ratio=1/3)

nofiber_days

nofiber_days %>% write_rds('../data/07_nofiber_days.RDS')
   
# compare the delta of the day 3 to 0, day 6 and 0. 
       
```



```{r}
# the trapezpid auc
dat_entero <- plotdf %>% 
  select(diet_treatment,
         abx_treatment,
         day,
         mouse_identifier,
         CFUs_per_GramStool)

dat_entero_wide <- dat_entero %>% 
  pivot_wider(id_cols = c(diet_treatment,
                          abx_treatment,
                          mouse_identifier),
              names_from = day,
              names_prefix = "day",
              values_from = CFUs_per_GramStool)
 
dat_entero_wide <- dat_entero_wide %>% 
  mutate(trap_0_3 = (day0  + day3 )*3/2,
         trap_3_6 = (day3  + day6 )*3/2,
         trap_6_9 = (day6  + day9 )*3/2,
         trap = trap_0_3 + trap_3_6 + trap_6_9,
         groups = paste(abx_treatment,
                         diet_treatment,sep="__")) %>% 
  mutate(groups = factor(groups, levels = c('DPBS__vehicle','DPBS__sucrose','biapenem__vehicle','biapenem__sucrose')))

# the boxplot of the AUC
my_comparisons <- list( c("DPBS__vehicle", "biapenem__vehicle"), 
                        c("biapenem__vehicle", "biapenem__sucrose"), 
                        c("DPBS__vehicle", "DPBS__sucrose"))

nofiber_AUC <- ggboxplot(dat_entero_wide,
          x="groups",add = 'jitter',
          y="trap", color  = 'groups', add.params = list(alpha = 0.5, shape = 16)) +
  ylab("Trapezoidal\nAUC")+xlab('') +
   scale_color_manual(values = c('gray76','#ffbcdc','gray32','deeppink2')) +
  scale_y_log10(breaks = c(1 %o% 10^(-1:8)),  labels = trans_format("log10", math_format(10^.x))) +
  stat_compare_means(comparisons = my_comparisons,label= "p.signif", method= 'wilcox.test',tip.length = 0.04,exact=T,correct=T) +
  theme(#axis.text.x = element_blank(),
        axis.title=element_text(size=10), 
        axis.text =  element_text(size = 10),legend.position = 'none',aspect.ratio=1/3.1, axis.ticks.x = element_blank())

nofiber_AUC     
```

# Final mouse graph 
 
## p1:healthy mice

```{r}
library(cowplot)
nofiber <- read_rds('../data/07_nofiber_days.RDS')
chow <- read_rds('../data/08_chow_days.RDS')
chow_auc <- read_rds('../data/08_chow_auc.RDS')
glucose <- read_rds('../data/05_f3_sugars_days.RDS')
long <- read_rds('../data/05_f3_five_days.RDS')
```


```{r}
title <- ggdraw() + 
  draw_label(
    "Fig. S15",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )  

# the hjust is to adjust the position of the label A, B....
chowones <- plot_grid(chow,chow_auc, 
                 label_size = 12, ncol = 2, labels = c('A','B'), hjust = 3.7,
                align = 'vh', axis = 'lrtb', rel_widths = c(2,1.2))

S_mouse1 <- plot_grid(chowones, NA, nofiber, NA, glucose,NA, long,
                  rel_heights = c(1,-0.2, 1, 0.1, 1, 0.3, 1),
                  hjust = -1.9,
                 label_size = 12, ncol = 1,labels = c(NA,'C','D','E'),
                align = 'vh', axis = 'lrtb')

  
combined <- plot_grid(
  title, S_mouse1,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))
 
ggsave('../results//S15_diet_mice_P1_R07.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)   
```

## p2: transplant mice (BM only mice)

```{r}
transplant <- read_rds('../data/02_transplant_CFU_plot.RDS')

title2 <- ggdraw() + 
  draw_label(
    "Fig. S15 (Continued)",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )  


S_mouse2 <- plot_grid(NA, transplant,
                  rel_heights = c(-0.2,1),
                  #hjust = -1.9,
                 label_size = 12, ncol = 1,
                align = 'vh', axis = 'lrtb')

 
combined <- plot_grid(
  title2, S_mouse2,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,5,1,1), "cm"))

ggsave('../results//S15_diet_mice_p2_R07.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)   
```

# the diet nutritional info (Table S4)

```{r}
# the no fiber diet and the control diet info
# just enter from the pdf by hand 
control_d <- tibble(
  `Energy (Kcal/g)` = 4.11,
  `Fiber percent of ration` = '4.4%',
  `Calories provided by protein` = '24.495%',
  `Calories provided by fat` = '13.122%',
  `Calories provided by carbohydrates` = '62.382%'
) %>% 
  gather('Control diet','value')


nofiber_d <- tibble(
  `Energy (Kcal/g)` = 4.10,
  `Fiber percent of ration` = 0,
  `Calories provided by protein` = '17.4%',
  `Calories provided by fat` = '15.4%',
  `Calories provided by carbohydrates` = '67.2%'
) %>% 
  gather('No fiber diet','value')
```

```{r}
# save them to tables and then combine
control_d %>% 
  kable() %>% 
  kable_styling(full_width = F) %>%  # Apply default styling
  row_spec(0, bold = TRUE) %>% 
  save_kable(
  '../data/07_control_d_tb.jpg',
  bs_theme = "simplex",
  self_contained = TRUE,
  extra_dependencies = NULL,
  latex_header_includes = NULL,
  keep_tex = FALSE,
  density = 300
)

nofiber_d %>% 
  kable() %>% 
  kable_styling(full_width = F) %>%  # Apply default styling
  row_spec(0, bold = TRUE) %>% 
  save_kable(
  '../data/07_nofiber_d_tb.jpg',
  bs_theme = "simplex",
  self_contained = TRUE,
  extra_dependencies = NULL,
  latex_header_includes = NULL,
  keep_tex = FALSE,
  density = 300
)

nofiber <- ggdraw() + draw_image("../data/07_nofiber_d_tb.jpg", scale = 0.8)
controldiet <- ggdraw() + draw_image("../data/07_control_d_tb.jpg", scale = 0.8)
 

title <- ggdraw() + 
  draw_label(
    "Table S4",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0)
  )

table_diets <- plot_grid(nofiber, controldiet, labels = c('A','B'), nrow = 1)

combined <- plot_grid(
  title, table_diets,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,10,1), "cm"))

ggsave('../results//Table_S4_two_diets_composition_R07.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300) 
```

  