---
title: "Clinical outcome"
output: html_document
date: "2024-07-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(LCAtoolbox)
library(gtsummary)
library(ggsurvfit)
library(tidycmprsk)
library(survival)
library(ggpubr)
library(gt)
library(cowplot)
library(survminer)
library(patchwork)
library(geepack)
```


# load the cleaned data

```{r}
# load("../data/df_main_Dec10.Rdata")
# link <- read_csv('../../MSS_pipeline-/scripts/food_tree/data/152_pid_match.csv')
# 
# df_main <- df_main |>
#   mutate(gvhdppx_CNI = as.numeric(gvhd_ppx == "CNI-based"),
#          gvhdppx_PTCy = as.numeric(gvhd_ppx == "PTCy-based"))
# 
# 
# colnames(df_main)
# df_main <- df_main %>%
#   select(source:gvhdppx_PTCy) %>%
#   mutate(mrn = as.numeric(mrn_str)) %>%
#   full_join(link) %>%
#   select(-d100_a_gvhd_onset, -mrn_str, -agvhd_onset,  -mrn) %>%
#   relocate(pid, .before = 'source')
# 
# df_main %>% write_rds('../data/R02_cleaned_clinical_outcome2.rds')

# the below table has the pid
df_main <- read_rds('../data/R02_cleaned_clinical_outcome2.rds') %>%
  mutate(modal_diet = as.character(modal_diet),
         modal_diet = if_else(modal_diet == 'High intake', 'Higher-intake', 'Lower-intake/sugar-enriched'),
         modal_diet = factor(modal_diet, levels = c( 'Lower-intake/sugar-enriched', 'Higher-intake'))) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(source_and_gvhdppx = str_glue('{source}+{gvhd_ppx}'),
         source_and_gvhdppx = factor(source_and_gvhdppx, levels = c('TCD+TCD','Cord+CNI-based','Unmodified+CNI-based','Unmodified+PTCy-based')),
         day_exposed_cat = factor(day_exposed_cat, levels = c('Short exposure (< 8 days)','Long exposure (>= 8 days)')))
df_main %>% count(source_and_gvhdppx)

# find out the abx exposure days

```
 
```{r}
colnames(df_main)
df_main %>% count(type_gvhd_simple)
df_main %>% count(type_gvhd)
```
 
# high sugar fraction in cluster 1 than cluster 2

```{r}
df_diet_pt <- read_rds('../data/10_df_diet_pt.RDS')

res <- geepack::geeglm(Sugar_fraction ~ Clusters + splines::ns(time,knots = quantile(df_diet_pt$time, probs=c(0.2,0.8))),
       id=pid, corstr="exch", data=df_diet_pt)
summary(res)
```
 
 
# OS model



```{r survival}
# since the below is not significant, so we will stick to the lower intake and higher intake survival curve
# higher_OS <- survfit2(Surv(OStime_30,OSevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "Higher-intake")) %>%
#   ggsurvfit(linewidth = 0.8) +
#   add_pvalue("annotation",size=5) +
#   add_risktable()+
#   ylab("Survival probability") +
#   xlab("Days relative to HCT, landmarked at day 12")+
#   ylim(c(0,1)) +
#   ggtitle("Patients with higher intake")+
#   theme(aspect.ratio = 1)
# 
# lower_OS <- survfit2(Surv(OStime_30,OSevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "Lower-intake/sugar-enriched")) %>%
#   ggsurvfit(linewidth = 0.8) +
#   add_pvalue("annotation",size=5) +
#   add_risktable()+
#   ylab("Survival probability") +
#   xlab("Days relative to HCT, landmarked at day 12")+
#   ylim(c(0,1)) +
#   ggtitle("Patients with lower intake (sugar-enriched)") +
#   theme(aspect.ratio = 1)
```

## survival 

```{r survival}
# survival between two clusters
OS_clusers <- survfit2(Surv(OStime_30,OSevent)~modal_diet  , data = df_main |> filter(OStime_30 > 0 )) %>%
  ggsurvfit(linewidth = 0.8) +
  add_pvalue("annotation",size=5) +
  add_risktable()+
  ylab("Survival probability") +
  xlab("Days relative to HCT, landmarked at day 12")+
   scale_color_manual(values = c( "darkslateblue",  "darkgoldenrod2"), name = '') +
  ylim(c(0,1)) +
  ggtitle("")+
  theme(aspect.ratio = 1/1.5, legend.position = c(0.5, 0.3))
OS_clusers

survival_plot <- list(
  ggsurvfit::ggsurvfit_build(OS_clusers)
) |> 
  wrap_plots()

# the multivariate model (the code gets a little bit too messy so I just put this here together with the univariate )
fit <- coxph(Surv(OStime_30,OSevent)~modal_diet*abx13  + intensity + source_and_gvhdppx,
             data = df_main |> filter(OStime_30 > 0 ) %>% mutate(abx13 = if_else(day_exposed>= 13, 'long', 'short'), abx13 = factor(abx13, levels = c('short','long'))))


fit |> 
  tbl_regression(exponentiate = FALSE) |> 
  bold_p() |> 
  as_gt()  |> 
  gtsave(filename="../data/09_OS_model_multi_inclu_carb.png")

# what is the distribution of the day exposed
summary(fit)
```

```{r}

# 
# dtb %>% ggscatter(x = 'Calories_kcal', y = 'estimated_cal') +
#   geom_abline( slope = 1, intercept = 0)

# Sugar Density (grams sugar/1000 kcal):
# calculate the density 

# the median for each patient
median_sugar_pt <- dtb %>% 
  group_by(pid) %>% 
  summarise(median_per_pt = median(dens_sugar, na.rm = T))

median_whole <- median(median_sugar_pt$median_per_pt, na.rm = T)

high_sugar_pts <- median_sugar_pt %>% 
  filter(median_per_pt >= median_whole) %>% 
  pull(pid)
```

## Table S3 model fit

```{r OS_model}
# rename the columns so that they look nice in the output table!
input_df <- df_main |> 
  filter(OStime_30 > 0) %>% 
  rename(`Diet-pattern cluster` = modal_diet,
         `Abx exposure(days)` =day_exposed,
         `Conditioning intensity` = intensity,
         Graft_type_and_GvHD_prophylaxis = source_and_gvhdppx) %>% 
  mutate(Graft_type_and_GvHD_prophylaxis = case_when(
    Graft_type_and_GvHD_prophylaxis == 'TCD+TCD' ~ 'T-cell depleted PBSC',
    Graft_type_and_GvHD_prophylaxis == 'Cord+CNI-based' ~ 'Cord blood + CNI-based',
    Graft_type_and_GvHD_prophylaxis == 'Unmodified+CNI-based' ~ 'Unmodified graft + CNI-based',
    Graft_type_and_GvHD_prophylaxis == 'Unmodified+PTCy-based' ~ 'Unmodified graft + PTCy-based'
  )) %>% 
  mutate(Graft_type_and_GvHD_prophylaxis = factor(Graft_type_and_GvHD_prophylaxis, levels = c('T-cell depleted PBSC','Cord blood + CNI-based','Unmodified graft + CNI-based','Unmodified graft + PTCy-based'))) %>% 
    rename(`Graft source and GvHD prophylaxis` = Graft_type_and_GvHD_prophylaxis) %>% 
   mutate(`Diet-pattern cluster` = case_when(
    `Diet-pattern cluster` == 'Lower-intake/sugar-enriched' ~ 'Cluster 1 (Lower-intake/sugar-enriched)',
    `Diet-pattern cluster` == 'Higher-intake' ~ 'Cluster 2 (Higher-intake)' 
  )) %>% 
  mutate(grp = if_else(pid %in% high_sugar_pts, 'high_sugar', 'lower_sugar'))


OS_clusers <- survfit2(Surv(OStime_30,OSevent)~grp  , data = input_df |> filter(OStime_30 > 0 )) %>%
  ggsurvfit(linewidth = 0.8) +
  add_pvalue("annotation",size=5) +
  add_risktable()+
  ylab("Survival probability") +
  xlab("Days relative to HCT, landmarked at day 12")+
   scale_color_manual(values = c( "darkslateblue",  "darkgoldenrod2"), name = '') +
  ylim(c(0,1)) +
  ggtitle("")+
  theme(aspect.ratio = 1/1.5, legend.position = c(0.5, 0.3))
OS_clusers

survival_plot <- list(
  ggsurvfit::ggsurvfit_build(OS_clusers)
) |> 
  wrap_plots()


fit <- coxph(Surv(OStime_30,OSevent)~grp*`Abx exposure(days)`  + `Conditioning intensity` + `Graft source and GvHD prophylaxis`,
             data= input_df)


# fit_original <- coxph(Surv(OStime_30,OSevent)~modal_diet*day_exposed  + intensity + source + gvhd_ppx,
#              data=df_main |> filter(OStime_30 > 0) ) 

fit |> 
  tbl_regression(exponentiate = FALSE) |> 
  bold_p() |> 
  as_gt() |> 
  gtsave(filename="../data/09_OS_model.png")


# just print the multivar table to the correct size

title <- ggdraw() + 
  draw_label(
    "Table S3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )


table_OS <- ggdraw() + draw_image("../data/09_OS_model.png", scale = .8)



combined <- plot_grid(
  title, table_OS,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/Table_S3_OS_multivariate_R09.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  
```
 
 
 
```{r}
coef(fit)[2]
```
 

```{r}
## The following lines construct a Wald test on the association between abx exposure and OS for high intake patients.
diff <- sum(coef(fit)[c(2,8)])
p <- aod::wald.test(Sigma=vcov(fit)[c(2,8),c(2,8)],
                    b=coef(fit)[c(2,9)],
                    L=t(c(1,1)))

## Visualizing associations between abx and OS for low and high intake patient groups:
loghr <- data.frame(exposure = 0:20,
                    hr = exp(c(coef(fit)[2]*0:20,
                               diff*0:20)),
                    group = c(rep("Low intake",21),
                              rep("High intake",21)),
                    ub = exp(c((coef(fit)[2]+sqrt(vcov(fit)[2,2])*1.96)*0:20,
                               (diff+1.96*sqrt(sum(vcov(fit)[c(2,8),c(2,8)])))*0:20)),
                    lb = exp(c((coef(fit)[2]-sqrt(vcov(fit)[2,2])*1.96)*0:20,
                               (diff-1.96*sqrt(sum(vcov(fit)[c(2,8),c(2,8)])))*0:20))
)
```

# abx_diet_logHR

```{r abx_VS_diet_logHR}
abx_diet_logHR <- loghr |> 
  mutate(group = if_else(group == 'Low intake', 'Lower-intake/sugar-enriched', 'Higher-intake'),
         group = factor(group, levels = c('Lower-intake/sugar-enriched','Higher-intake'))) %>% 
  ggplot(aes(x=exposure,y=hr)) + 
  geom_line(aes(color=group), size = 1.5)+
  geom_ribbon(aes(ymin=lb,ymax=ub),alpha=0.2) +
  geom_hline(yintercept = 1,color="black",linetype=2)+
  scale_y_continuous(transform = "log",labels=function(x) sprintf("%.0f", x))+
  #facet_grid(.~group, labeller = labeller(facet_var = c("Higher intake" = "Lower intake", "Lower intake" = "Higher intake"))) +
  facet_grid(.~group) +
  ylab("log(Hazard ratio) of death\ncompared to non-exposure patients") + 
  xlab("Number of days exposed to broad-spectrum\nantibiotics between day -7 to 12\nrelative to transplant") + theme_light()+
  scale_color_manual(values = c( "darkslateblue", 'darkgoldenrod2'), name = '') +
  theme(aspect.ratio = 1,  legend.position = 'none') 
     
abx_diet_logHR
```

# ignored for now

```{r}
tidycmprsk::cuminc(Surv(tevent_30,TRMevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "Higher intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="TRM") +
  add_risktable()+
  ylab("TRM cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.15))+
  ggtitle("Patients with high intake")

tidycmprsk::cuminc(Surv(tevent_30,TRMevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "Low intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="TRM") +
  add_risktable()+
  ylab("TRM cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.15))+
  ggtitle("Patients with low intake")



fitTRM <- crr(Surv(tevent_30,TRMevent) ~ as.factor(modal_diet)*day_exposed + source + intensity + gvhdppx_PTCy, data=df_main |> filter(tevent_30 > 0)) |>
  tbl_regression(exponentiate = FALSE) |>
  bold_p() |>
  as_gt() |>
  gtsave(filename="../data/TRM_model.html")

tidycmprsk::cuminc(Surv(tevent_30,GRMevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "High intake"& source!="TCD")) %>%
  ggcuminc(linewidth = 0.8, outcome="GRM") +
  add_risktable()+
  ylab("GRM cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.15))+
  ggtitle("Non-TCD Patients with high intake")

tidycmprsk::cuminc(Surv(tevent_30,GRMevent)~day_exposed_cat, data = df_main |> filter(OStime_30 > 0 & modal_diet == "Low intake"& source!="TCD")) %>%
  ggcuminc(linewidth = 0.8, outcome="GRM") +
  add_risktable()+
  ylab("GRM cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.15))+
  ggtitle("Non-TCD Patients with low intake")

fitGRM <- crr(Surv(tevent_30,GRMevent)~as.factor(modal_diet)*day_exposed + source + intensity + gvhd_ppx,data=df_main |> filter(tevent_30 > 0 & source!="TCD")) |>
  tbl_regression(exponentiate = FALSE)|>
  bold_p() |>
  as_gt() |>
  gtsave(filename="../data/GRM_model.html")


tidycmprsk::cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~modal_diet, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0)) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_pvalue("annotation",size=5) +
  add_risktable()+
  # scale_color_manual(values=c("blue","red"))+
  ylab("aGVHD onset cumulative incidence") +
  xlab("Days relative to HCT (Landmarked at day 12)")+
  ylim(c(0,0.8))

tidycmprsk::cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~day_exposed_cat, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0 & modal_diet == "High intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_risktable()+
  ylab("aGVHD onset cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.8))+
  ggtitle("Patients with high intake")

tidycmprsk::cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~day_exposed_cat, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0 & modal_diet == "Low intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_risktable()+
  ylab("aGVHD onset cumulative incidence") +
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.8))+
  ggtitle("Patients with low intake")

ggsave("../data/aGVHDonset.pdf")

fitAGVHD <- crr(Surv(tgvhd_event-12,type_gvhd_simple)~modal_diet + day_exposed + intensity + source + gvhd_ppx, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0)) |>
  tbl_regression(exponentiate = FALSE)|>
  bold_p() |>
  as_gt() |>
  gtsave(filename="../data/aGVHDonset_model.html")
list.files('~/Work/projects/MSS_pipeline-/scripts/food_tree/data/')
```

#  now F3

```{r}
# the legend for the stacked bar graph
bar_leg <-  plot_grid(ggpubr::get_legend(Average_intake))
ggsave('../data/09_bar_leg.pdf')
```

```{r}
title <- ggdraw() + 
  draw_label(
    "Fig. 3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 5)
  )

top <- plot_grid(pdiet2, pdiet2_comp, Average_intake_plot, Average_composition,
                 label_size = 12, ncol = 2,labels = c('A','B','C','D'),
                align = 'vh', axis = 'lrtb')




bottom <- plot_grid(survival_plot, abx_diet_logHR,
                 label_size = 12, ncol = 2,labels = c('E','F'),rel_widths  = c(1,1),
                align = 'vh', axis = 'lrtb')

all <- plot_grid(top, bottom, align = 'vh', axis = 'lrtb', nrow = 2, rel_heights = c(2,1.5))
 
combined <- plot_grid(
  title, all,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.05, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/09_clinical_outcome.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  
```



  

# revised a-gvhd onset analysis

```{r}
library(tidyverse)
library(LCAtoolbox)
library(gtsummary)
library(ggsurvfit)
library(tidycmprsk)
library(survival)
library(ggpubr)
library(gt)
library(cowplot)
library(survminer)
library(patchwork)
load('../data/df_main_Sep18.Rdata')
  
df_main <- df_main %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>% 
  mutate(source_and_gvhdppx = str_glue('{source}+{gvhd_ppx}')) %>%
  mutate(modal_diet = as.character(modal_diet),
         modal_diet = if_else(modal_diet == 'High intake', 'Higher-intake', 'Lower-intake/sugar-enriched'),
         modal_diet = factor(modal_diet, levels = c('Lower-intake/sugar-enriched','Higher-intake'))) 

df_main %>% count(type_gvhd_simple, agvhd_grade)
colnames(df_main)
# day_exposed : Number of days exposed to broad-spectrum\nantibiotics between day -7 to 12\nrelative to transplant
# leng_of_stay

# the range of the follow up dates
df <- df_main  %>% 
  select(where(is.Date)) %>% 
  gather()

df_main %>% 
  ggboxplot(x = 'modal_diet', y = 'day_exposed', add = 'jitter') +
  stat_compare_means()
```

## aGVHD onset cumulative incidence ~ modal_diet

```{r}
# aGVHD onset cumulative incidence ~ modal_diet
cuminc_cluster <- cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~modal_diet, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0)) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_risktable()+
   scale_color_manual(values = c(   "darkgoldenrod2", "darkslateblue"), name = '') +
  ylab("aGVHD onset cumulative incidence") +
  xlab("Days relative to HCT (Landmarked at day 12)")+
  ylim(c(0,0.8))


cuminc_cluster_plot <- list(
  ggsurvfit::ggsurvfit_build(cuminc_cluster)
) |> 
  wrap_plots()

cuminc_cluster_plot
```


```{r}
# aGVHD onset cumulative incidence ~ modal_diet
# high intake
tidycmprsk::cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~day_exposed_cat, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0 & modal_diet == "High intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_risktable()+
  ylab("aGVHD onset cumulative incidence") + 
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.8))+ 
  ggtitle("Patients with high intake")
```


```{r}
# aGVHD onset cumulative incidence ~ modal_diet
# low intake
tidycmprsk::cuminc(Surv(tgvhd_event-12,type_gvhd_simple)~day_exposed_cat, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0 & modal_diet == "Low intake")) %>%
  ggcuminc(linewidth = 0.8, outcome="aGVHD") +
  add_risktable()+
  ylab("aGVHD onset cumulative incidence") + 
  xlab("Days relative to HCT, landmarked at day 12")+
  ylim(c(0,0.8))+ 
  ggtitle("Patients with low intake")
```

## aGVHDonset : multivariate

```{r}
# aGVHDonset : multivariate
fitAGVHD <- crr(Surv(tgvhd_event-12,type_gvhd_simple)~modal_diet + day_exposed + intensity + source_and_gvhdppx, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0)) |> 
  tbl_regression(exponentiate = FALSE)|> 
  bold_p() |> 
  as_gt() |> 
  gtsave(filename="../data/aGVHDonset_model_multi.png")

# I tried the interactive version: modal_diet * day_exposed and the interaction term is not significant, so I can just have them as indenpendent ones. 
```

## aGVHDonset : univariate

```{r}
# aGVHDonset : univariate
fitAGVHD <- crr(Surv(tgvhd_event-12,type_gvhd_simple)~modal_diet, data = df_main |> filter(source!="TCD" & tgvhd_event-12 > 0)) |> 
  tbl_regression(exponentiate = FALSE)|> 
  bold_p() |> 
  as_gt() |> 
  gtsave(filename="../data/aGVHDonset_model_univariate.png")  
```

## R3 figure 

```{r}
# I think it would be a good idea to make this R only figure including the c i curve with the two clusters and the multivariate model with the crr
 title <- ggdraw() + 
  draw_label(
    "Fig. R3",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0)
  )

aGVHDonset_model_uni <- ggdraw() + draw_image("../data/aGVHDonset_model_univariate.png", scale = 0.9)

aGVHDonset_model_multi <- ggdraw() + draw_image("../data/aGVHDonset_model_multi.png", scale = 0.9)

bottom <- plot_grid(aGVHDonset_model_uni, aGVHDonset_model_multi,   nrow = 1, align = 'vh', axis = 'lrtb', labels = c('B', 'C'), rel_widths = c(2, 2))

plot_ <- plot_grid(cuminc_cluster_plot, bottom,  nrow = 2, align = 'vh', axis = 'lrtb', labels = c('A', NA) )

combined <- plot_grid(
  title, plot_,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,1,1), "cm"))

ggsave('../data/Fig_R3_aGVHD_onset.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = combined, dpi = 300)  
ggsave('../data/Fig_R3_aGVHD_onset.png',
      width = 210, height = 297, units = "mm", device = 'png', plot = combined, dpi = 300)  
```

