---
title: "Define patients trajectory clusters"
output: html_document
date: "2025-05-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(LCAtoolbox)
library(gtsummary)
library(ggsurvfit)
library(tidycmprsk)
library(survival)
library(ggpubr)
library(cowplot)
```

# run the trajectory algorithm

```{r}
df_pt <- readr::read_csv("~/Work/projects/MSS_pipeline-/scripts/food_tree/data/156_combined_PTB_original.csv")
df_diet <- readr::read_csv("~/Work/projects/MSS_pipeline-/scripts/food_tree/data/152_combined_DTB.csv")
df_med <- readr::read_csv("~/Work/projects/MSS_pipeline-/scripts/food_tree/data/169_all_medication.csv")
df_prophylaxis <- readr::read_csv("~/Work/projects/MSS_pipeline-/scripts/food_tree/data/for_angel_new_column.csv") 

df_diet_pd <- df_diet |> 
  group_by(mrn,fdrt) |> 
  filter(fdrt <= 12 & fdrt >= -7) |> 
  summarise(Protein_g = log(sum(Protein_g)+1),
            Fat_g = log(sum(Fat_g)+1),
            Carbohydrates_g = log(sum(Carbohydrates_g)+1),
            Fibers_g = log(sum(Fibers_g)+1),
            Sugars_g = log(sum(Sugars_g)+1)) |> 
  arrange(mrn,fdrt) |> 
  mutate(logProtein = log(Protein_g+1e-1),
         logFat = log(Fat_g+1e-1),
         logCarb = log(Carbohydrates_g+1e-1),
         logFiber = log(Fibers_g+1e-1),
         logSugar = log(Sugars_g+1e-1),
         isProtein = as.numeric(Protein_g > 0),
         isFat = as.numeric(Fat_g > 0),
         isCarb = as.numeric(Carbohydrates_g > 0),
         isFiber = as.numeric(Fibers_g > 0),
         isSugar = as.numeric(Sugars_g > 0)) |> 
  rename(Protein=Protein_g,
         Fat=Fat_g,
         Carb=Carbohydrates_g,
         Fiber=Fibers_g,
         Sugar=Sugars_g)

df_diet_pd |> 
  pivot_longer(cols=Protein:isSugar) |> 
  ggplot(aes(x=fdrt,y=value,group=mrn)) +
  geom_line(alpha=0.1) +
  facet_wrap(.~name,scales="free")

df_diet_pd <- df_diet_pd |> 
  ungroup() |> 
  left_join(df_pt) |> 
  rename(id=mrn,
         time=fdrt) |> 
  group_by(id) |> 
  mutate(num_obs = row_number()) |> 
  arrange(id, time)

library(tidyverse)
library(ggplot2)
library(LCAtoolbox)
library(gtsummary)

df_med <- df_med |> 
  filter(drug_name_clean %in% c("vancomycin", 
                                "imipenem_cilastatin",
                                "meropenem",
                                "ertapenem", 
                                "cefepime", 
                                "linezolid",
                                "metronidazole",
                                "piperacillin_tazobactam")) |> 
  filter(together != "vancomycin__IVPB") |> 
  full_join(df_pt, by="mrn") |> 
  mutate(start = start_date - hct,
         stop = stop_date - hct)

ddist <- sapply(-7:12,function(x) as.numeric(df_med$start <= x & df_med$stop >= x))
colnames(ddist) <- paste("Day",-7:12)
ddist <- data.frame(ddist,check.names = FALSE)
ddist[is.na(ddist)] <- 0
ddist$mrn <- df_med$mrn

df_abx <- ddist %>% 
  gather(v,value,`Day -7`:`Day 12`) %>%
  # filter(value == 1) %>% 
  separate(v, c("name1", "name2"), sep=" ") %>%
  mutate(Day = as.numeric(name2)) %>% 
  select(-name1,-name2) %>% 
  distinct() |> 
  group_by(mrn,Day) |> 
  summarise(abx = as.numeric(sum(value) > 0)) |> 
  rename(time=Day,
         id=mrn)|> 
  ungroup() |> 
  group_by(id) |> 
  mutate(num_obs = row_number()) |> 
  mutate(day_exposed = sum(abx)) |> 
  ungroup()

dat_diet <- model.matrix(~.+splines::ns(time,knots=c(quantile(unique(df_diet_pd$time),c(0.1,0.5,0.9)))),data=df_diet_pd)
colnames(dat_diet)[37:40] <- paste0("time",1:4)
dat_diet <- data.frame(dat_diet,check.names = FALSE)

fitdiet <- SLTCA(dat_diet,
                 num_class=2,
                 covx=NULL,
                 vary=c("Fat",
                        "Sugar",
                        "Fiber",
                        "Protein"),
                 covgee=c("time1","time2","time3","time4"),
                 Y_dist=c(rep("normal",4)),
                 varest=TRUE,
                 verbose=TRUE,
                 stop.rule="tau",
                 cor="ind",
                 maxiterEM=100,
                 tolEM=1e-4,
                 keep.switch = F)

fitdiet$beta$time1[2,1] + 1.96*fitdiet$ASE$betarb["Class 1 Sugar time1",]
fitdiet$beta$time1[2,1] - 1.96*fitdiet$ASE$betarb["Class 1 Sugar time1",]

fitdiet$beta$time1[2,2] + 1.96*fitdiet$ASE$betarb["Class 2 Sugar time1",]
fitdiet$beta$time1[2,2] - 1.96*fitdiet$ASE$betarb["Class 2 Sugar time1",]

timevec = unique(sort(dat_diet$time))
timespl = cbind(1,splines::ns(timevec,knots=c(quantile(unique(dat_diet$time),c(0.1,0.5,0.9)))))

Coef = matrix(unlist(fitdiet$beta),ncol=5,nrow=8)
pred <- timespl %*% t(Coef)

colnames(pred) <- c(paste0(c("Fat",
                             "Sugar",
                             "Fiber",
                             "Protein"),"_1"),
                    paste0(c("Fat",
                             "Sugar",
                             "Fiber",
                             "Protein"),"_2"))

df_pred1 <- data.frame(time=timevec,
                       pred,
                       check.names = FALSE)

df_pred_long2 <- df_pred1 |>  
  pivot_longer(cols = -time) 

df_pred_long2$event = sapply(df_pred_long2$name, function(x) strsplit(x,"_")[[1]][1])
df_pred_long2$modal_diet = sapply(df_pred_long2$name, function(x) strsplit(x,"_")[[1]][2])
df_pred_long2$event = factor(df_pred_long2$event)

modal <- data.frame(newid=as.numeric(names(fitdiet$modal)), modal=fitdiet$modal)
dat_diet$modal_diet = NA
dat_diet$modal_diet[modal$newid] = modal$modal
dat_diet <- dat_diet %>%
  group_by(id) %>%
  mutate(modal_diet = first(modal_diet))

df_class <- dat_diet |> 
  select(id,modal_diet) |> 
  distinct()

# df_abx <- df_abx |> 
#   left_join(df_class) #|> 
# #mutate(modal_abx = ifelse(day_exposed == 0,4,modal_abx))
# 
# df_class <- df_abx |> 
#   select(id,modal_diet) |> 
#   distinct()

df_diet_pd <- df_diet_pd |> 
  left_join(df_class)

pdiet <- df_pred_long2 |> 
  ggplot(aes(x=time,
             y=value,
             color=modal_diet)) + 
  geom_line() +
  facet_grid(event~.,scales="free_y")+
  ylab("Log-transformed daily intake (grams)") +
  xlab("Days relative to HCT") + 
  ylab("")
```

# S10 A 

```{r}
first2_ratio <- 2
line_size = 1

pdiet2 <- df_diet_pd |> 
  pivot_longer(cols=c("Fat",
                      "Sugar",
                      "Fiber",
                      "Protein"),
               values_to = "value",
               names_to = "event") |>
  mutate(modal_diet = if_else(modal_diet == 1, 'Cluster 1', 'Cluster 2')) %>% 
  rename(Clusters = modal_diet) |> 
  ggplot(aes(x=time,y=exp(value))) + 
  geom_line(aes(group=id),alpha=0.03) + 
  facet_grid(Clusters~ event) + 
  geom_line(data=df_pred_long2 |> mutate(modal_diet = if_else(modal_diet == 1, 'Cluster 1', 'Cluster 2')) %>%  rename(Clusters = modal_diet) ,aes(x=time,y=exp(value),color=Clusters) , size = line_size) +
  theme_light() +
  labs(x = 'HCT Day', y = 'Daily intake (grams)') +
  scale_y_log10() +
  scale_color_manual(values = c("darkslateblue", "darkgoldenrod2")) +
  theme(aspect.ratio = first2_ratio, legend.position = 'none')
pdiet2
```

# F3 A,B and S10 B

## the density metric

```{r}
df_density <- read_csv('../data/152_combined_DTB.csv') %>%
  select(pid, fdrt,description,  Calories_kcal:Sugars_g) %>%
  select(-total_weight) %>%
  group_by(pid, fdrt ) %>% 
  summarise(d_carb = sum(Carbohydrates_g),
            d_Protein_g = sum(Protein_g),
            d_Fat_g = sum(Fat_g),
            d_Calories_kcal = sum(Calories_kcal),
            d_Fibers_g = sum(Fibers_g),
            d_Sugars_g = sum(Sugars_g)) %>% 
  filter(d_Calories_kcal > 0) %>% # to get rid of spurious results because of mathematical manipulatio
  mutate(dens_Protein = round(d_Protein_g/(d_Calories_kcal )*1000, 2),
         dens_carb = round(d_carb/(d_Calories_kcal )*1000, 2),
         dens_fat = round(d_Fat_g/(d_Calories_kcal )*1000, 2),
         dens_fiber = round(d_Fibers_g/(d_Calories_kcal )*1000, 2),
         dens_sugar = round(d_Sugars_g/(d_Calories_kcal )*1000, 2)) %>% 
  rowwise( ) %>% 
  mutate(dens3 = dens_Protein + dens_carb + dens_fat) %>% 
  mutate(log_den_sugar = log(dens_sugar + 0.5),
        log_den_fiber = log(dens_fiber + 0.5),
        log_den_3 = log(dens3 + 0.5)) 

p_cal <- df_density %>% 
  filter(fdrt %in% -7:12) %>% 
  left_join(readr::read_csv("~/Work/projects/MSS_pipeline-/scripts/food_tree/data/156_combined_PTB.csv") %>% select(pid, modal_diet)) %>%  # the original cluster label 
  mutate(pid = as.factor(pid), 
         modal_diet = factor(modal_diet, levels = c('cluster2:higher-intake','cluster 1:lower-intake/sugar-enriched')))

cluster_cal <- p_cal %>% 
  mutate(modal_diet = factor(modal_diet, levels = c('cluster 1:lower-intake/sugar-enriched', 'cluster2:higher-intake'))) %>% 
  ggboxplot(x = 'fdrt', y = 'd_Calories_kcal', outlier.shape = NA,xlab = '',
            #add = 'jitter', add.params = list(alpha = 0.2, shape = 16), 
            title = 'calories') +
  stat_summary(fun = median, geom = "line", aes(group = 1), color = "red", size = 1) +scale_x_discrete( breaks = seq(0, 10, 10)) +
  facet_wrap(~ modal_diet)+theme_bw() +  theme(aspect.ratio = 3.5)

cluster_cal 
```
```{r}
# carbohydrate should be the total carbohydrate meaning it includes the sugar and fiber #!!!!!!!  
# combine the fiber and the carb
df_g_prop <- p_cal %>% 
  #select(-starts_with('dens')) %>% 
  select(-d_Calories_kcal)


# carbohydrate should be the total carbohydrate meaning it includes the sugar and fiber #!!!!!!!  
# calculate the new metrics
df_clean <- df_g_prop |> 
  mutate(
    # First, get the denominator: the total mass of the 3 key macros
    # We treat this as the "whole" for our proportion calculations
    macro_sum = d_carb + d_Protein_g + d_Fat_g,
    
    # Now calculate the shares relative to that sum.
    # We use a wrapper like if_else or case_when to handle cases where 
    # macro_sum is 0 (like water or diet soda) to avoid dividing by zero.
    sugar_prop = if_else(macro_sum > 0, d_Sugars_g / macro_sum, 0),
    
    # "Other carb" is just total carbs minus the sugar part
    other_carb_prop = if_else(macro_sum > 0, (d_carb - d_Sugars_g) / macro_sum, 0),
    
    fat_prop = if_else(macro_sum > 0, d_Fat_g / macro_sum, 0),
    
    protein_prop = if_else(macro_sum > 0, d_Protein_g / macro_sum, 0)
  ) %>% 
  select(pid, fdrt, modal_diet, ends_with('prop') ) |> 
  gather('event','prop', sugar_prop:protein_prop) %>% 
  mutate(fdrt = factor(fdrt)) %>% 
  mutate(cluster_label = if_else(modal_diet == 'cluster2:higher-intake', '2higher','1lower')) %>% 
  split(.$event)

df_clean
```

```{r}
prop_plots <- df_clean %>% 
  imap(function(df, .y){
      
     ggplot(df, aes(x = fdrt, y = prop, fill = modal_diet, color = modal_diet)) +
        geom_boxplot(
          outlier.shape = NA,    
          outlier.size = 1,    
          outlier.alpha = 0.5,   
          outlier.color = "red" 
        ) +
        labs(title = str_glue('{.y}'),y = 'Daily intake (proportion)',x = 'HCT Day') +
        stat_summary(fun = median, geom = "line", aes(group = 1), color = 'red', size = .5) +
        scale_x_discrete( breaks = seq(0, 10, 10)) +
      ylim(0,1) +
  scale_color_manual(values = c( "darkgoldenrod2", "darkslateblue")) +
  scale_fill_manual(values = c("darkgoldenrod2", "darkslateblue")) +
        facet_wrap(~ cluster_label ) +theme_bw()  +  theme(aspect.ratio = 3.5, legend.position = 'none', strip.text = element_blank())
     
  })  
combined <- plot_grid(plotlist = prop_plots, nrow = 1)
combined
```
```{r}
res <- plot_grid(
  '', combined,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(1,1,1,3), "cm"))

ggsave('../data/R10_clinical_proportions.pdf',
      width = 210, height = 297, units = "mm", device = 'pdf', plot = res, dpi = 300)  
```

```{r}    
# to calculate a p value between the two clusters in each macronutrient **proportions** 
# compared to "cluster2:higher-intake"
each_res_prop <- df_clean %>% 
  map(function(df){ 
    df_ <- df %>% mutate(fdrt = as.numeric(as.character(fdrt)))
    res_each_prop <- geepack::geeglm(prop ~ modal_diet + splines::ns(fdrt,knots = quantile(df_$fdrt, probs=c(0.2,0.8))),
       id=pid, corstr="exch", data=df_)
    return(summary(res_each_prop)$coefficients[2,c(1,4)])
  }) %>% bind_rows(.id = 'event') %>% 
  mutate(padj = p.adjust(`Pr(>|W|)`)) %>% 
  arrange(padj, Estimate) |> 
  mutate(Estimate = round(Estimate, 2))

each_res_prop
```