---
title: "Estimating lactose effect"
author: "Anqi Dai"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggpubr)
library(tidybayes)  
library(brms)
library(rstan)
library(ggtext)
library(janitor)
library(cowplot)
options(mc.cores = parallel::detectCores())
ncores = parallel::detectCores()
rstan_options(auto_write = TRUE)
```

# what food codes have high, moderate or low lactose

```{r}
levels_ <- read_csv('../data/194_g3_milk_codes_grouping.csv')

g_milk <- read_csv('../data/152_combined_DTB.csv') %>% 
  distinct(Food_NSC, Food_code, description) %>% 
  mutate(Food_code = as.character(Food_code)) %>% 
  filter(str_detect(Food_code, '^1')) %>% 
  arrange(Food_code)

g3 <- read_delim('../data/NodeLabels.txt') %>% 
  clean_names() %>% 
  mutate(level_code = as.character(level_code)) %>% 
  filter(str_length(level_code) == 3 & str_detect(level_code, '^1')) %>%
  rename(g3 = level_code)

unique_codes <- g_milk %>% distinct(Food_code, description)%>% 
  arrange(Food_code) %>% 
  # further differentiate to the second digit 
  mutate(g3 = str_sub(Food_code, end = 3)) %>% 
  inner_join(g3)

g3_unique <- unique_codes %>% 
  left_join(levels_ %>% mutate(g3 = as.character(g3)), by = join_by(g3, main_food_description))
```



```{r}
dtb <- read_csv('../data/152_combined_DTB.csv') %>% mutate(Food_code = as.character(Food_code))

macronutrients_sugar_group <- dtb %>%
  select(pid, fdrt, Food_code, Sugars_g) %>%
  group_by(pid, fdrt,Food_code) %>%
  summarise(total_daily_code_sugar = sum(Sugars_g)) %>%
  left_join(g3_unique %>% select(Food_code, lactose_level)) %>% 
  mutate(lactose_level = if_else(is.na(lactose_level), 'other',lactose_level)) %>% 
  ungroup()

# summarize the prior two days of sugar intake in these groups 

mean_p2d_sugar_group <-  function(pid_, p1d_, p2d_){
  df = macronutrients_sugar_group %>%
    filter(pid == pid_) %>%
    filter(fdrt %in% c(p1d_, p2d_  )) %>%
    group_by(pid, lactose_level) %>%
    summarise(ave_sugar_grp = sum(total_daily_code_sugar)/2)
  return(df)
}
```


```{r}
meta <- read_csv('../data/153_combined_META.csv')

stb_pair <- meta %>%
  select(pid, sdrt) %>%
  transmute(pid = pid,
            p1d = sdrt-1,
            p2d = sdrt-2)


mean_p2d_sugar_group_df <- pmap(stb_pair, function(pid, p1d, p2d){
    mean_p2d_sugar_group(pid, p1d, p2d)
  }) %>%
  set_names(meta %>% pull(sampleid)) %>%
  bind_rows(.id = 'sampleid')

p2d_sugar <- mean_p2d_sugar_group_df %>% 
  mutate(lactose_level = str_glue('sugar_{lactose_level}')) %>% 
  spread('lactose_level','ave_sugar_grp', fill = 0)



```


```{r}
# use the df I already have from 090 and just replace the sugar column with ones from here 
full <- read_csv('../data/090_all_samples1009_meta_p2d_fg9_dietall_genera90_pid.csv') %>%    
  select(pid, sdrt,timebin,  sampleid,simpson_reciprocal, empirical, EN, TPN, intensity,  Enterococcus, ave_fiber:ave_fat) %>% 
  inner_join(p2d_sugar, by = join_by(pid, sampleid)) %>% 
  # here the sugar subgroups need to be divided by 100
  mutate(sugar_high = sugar_high/100, 
         sugar_low = sugar_low/100,
         sugar_moderate = sugar_moderate/100,
         sugar_other = sugar_other/100) %>% 
  mutate(abx = if_else(empirical == 'TRUE', 1, 0),
         TPN = if_else(TPN == 'TRUE', 1, 0),
         EN = if_else(EN == 'TRUE', 1, 0)) %>% 
  mutate(intensity = factor(intensity, levels = c('nonablative','reduced','ablative'))) %>%
  mutate(      ave_fiber_e= ave_fiber*abx,
                ave_fat_e=ave_fat*abx,
                ave_sugar_high_e=sugar_high*abx,
               ave_sugar_low_e=sugar_low*abx,
               ave_sugar_moderate_e=sugar_moderate*abx,
               ave_sugar_other_e=sugar_other*abx
          )
```


# Enterococcus outcome model

```{r}
enterococcus_cls <- read_csv('../data/171_genus_CLR_res.csv') %>% 
  filter(genus %in% c('Enterococcus')) %>% 
  rename(Enterococcus_clr = clr)

full_entero <- full %>% 
  inner_join(enterococcus_cls %>% select(-genus)) %>% 
  select(-Enterococcus)

priors_Enterococcus_macro_sugar_group <- c(
            # for the macro nutrients
            prior(normal(0, 1), class = 'b', coef = "ave_fiber"),
            prior(normal(0, 1), class = 'b', coef = "ave_fat"),
            prior(normal(0, 1), class = 'b', coef = "sugar_high"),
            prior(normal(0, 1), class = 'b', coef = "sugar_low"),
            prior(normal(0, 1), class = 'b', coef = "sugar_moderate"),
            prior(normal(0, 1), class = 'b', coef = "sugar_other"),
            # for the interaction terms
            prior(normal(0, 1), class = 'b', coef = "ave_fiber_e"),
            prior(normal(0, 1), class = 'b', coef = "ave_fat_e"),
            prior(normal(0, 1), class = 'b', coef = "ave_sugar_high_e"),
            prior(normal(0, 1), class = 'b', coef = "ave_sugar_low_e"),
            prior(normal(0, 1), class = 'b', coef = "ave_sugar_moderate_e"),
            prior(normal(0, 1), class = 'b', coef = "ave_sugar_other_e"),
            # for the TPN 
            prior(normal(0, 0.1), class = 'b', coef = "TPN"),
            # for the EN
            prior(normal(0, 0.1), class = 'b', coef = "EN"),
            # for the empirical 
            prior(normal(0, 0.5), class = 'b', coef = "abx"))

Enterococcus_macro_sugar_group <- Enterococcus_clr ~ 0 +
                ave_fiber_e +
                ave_fat_e +
                ave_sugar_high_e +
                ave_sugar_low_e +
                ave_sugar_moderate_e +
                ave_sugar_other_e +
                ave_fiber +
                ave_fat +
                sugar_high + 
                sugar_low +
                sugar_moderate +
                sugar_other +
               abx+
               intensity +
                TPN+
                EN+
               (1 | pid) +
                (1 | timebin)

mod_entero <-  brm(Enterococcus_macro_sugar_group,  
                data = full_entero, 
              warmup = 1000, iter = 3000, 
              prior = priors_Enterococcus_macro_sugar_group,
              cores = ncores, 
              chains = 2, 
              control = list(adapt_delta = 0.99),
              seed = 456, file = '13_entero_model_macro_sugar_group_post_interaction')

post_res <- suppressWarnings(posterior_samples(mod_entero)) 
post_res %>%  write_csv('../data/13_entero_model_macro_sugar_group_post_interaction.csv')
```
 
# plotting    

```{r}
matchingtb <- read_rds('../data/196_matching_shortname.rds')

post_coeff <- post_res %>% 
  select(starts_with('b_')) %>% 
  #select(contains( 'sugar')) %>% 
  gather('item', 'coeff')

post_sugar_grp <-  post_coeff %>% 
  filter(!str_detect(item, 'intensity')) %>% 
  mutate(item = str_replace(item, 'b_ave_',''),
         item = str_replace(item, 'b_','')) %>% 
  mutate(shortname = case_when(
        item ==  'fiber_e' ~ 'abx * Fiber',  
    item == 'fiber' ~ 'Fiber',
    item ==  'fat_e' ~ 'abx * Fat',
    item ==  'fat' ~ 'Fat',
    item == 'sugar_high_e' ~ 'abx * Sugar from milk products with high lactose content',
    item == 'sugar_high' ~ 'Sugar from milk products with high lactose content',
     item == 'sugar_low_e' ~ 'abx * Sugar from milk products with low lactose content',
    item == 'sugar_low' ~ 'Sugar from milk products with low lactose content',
     item == 'sugar_moderate_e' ~ 'abx * Sugar from milk products with moderate lactose content',
    item == 'sugar_moderate' ~ 'Sugar from milk products with moderate lactose content',
     item == 'sugar_other_e' ~ 'abx * Sugar from non-milk products',
    item == 'sugar_other' ~ 'Sugar from non-milk products',
    item ==  'nonablative' ~ 'Nonablative',
    item ==  'reduced' ~ 'Reduced',
    item ==  'ablative' ~ 'Ablative',
    item ==  'TPN' ~ 'TPN',
    item ==  'EN' ~ 'EN',
    item ==  'abx' ~ 'abx'
  )) 

macro_order <- c('Fat','abx * Fat',
                 'Fiber','abx * Fiber',
                 'Sugar from non-milk products','abx * Sugar from non-milk products',
                 'Sugar from milk products with low lactose content','abx * Sugar from milk products with low lactose content',
                 'Sugar from milk products with moderate lactose content','abx * Sugar from milk products with moderate lactose content',
                 'Sugar from milk products with high lactose content','abx * Sugar from milk products with high lactose content',
                 "TPN" ,"EN" , 'abx')


interaction_terms_macro <- tibble(
  shortname = macro_order
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         interaction_fill = 'interaction_fill')

blue_terms_macro <- tibble(
  shortname = macro_order
) %>% 
  mutate(ymin = seq(1, nrow(.)) - 0.5,
         ymax = seq(1, nrow(.)) + 0.5) %>% 
  filter(!str_detect(shortname, '\\*')) %>% 
  mutate(xmin = -Inf, xmax = Inf,
         blue_fill = 'blue_fill')
```


```{r}
zero_line_size = .8

macro_lactose <- post_sugar_grp %>% 
  mutate(shortname = factor(shortname, levels = macro_order)) %>% 
  #left_join(cross0) %>% 
  ggplot() +
   stat_pointinterval(aes(x = coeff, y = shortname), .width = .95, fatten_point = 1.2) +
  geom_rect(data = interaction_terms_macro, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = interaction_fill), alpha = .3) +
  geom_rect(data = blue_terms_macro, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = blue_fill) , alpha = .1) +
  scale_fill_manual(values=c("interaction_fill" = "#6B8E2320", "blue_fill" = "#6B8E2340")) +
  #scale_color_manual(values = c("#EC0000", "black")) +
  scale_y_discrete( labels = function(x) { ifelse(str_detect(x, '\\*'),  str_glue("<b style='color:royalblue'>{x}</b>"), as.character(x)) }) +
  geom_vline(xintercept = 0, col = 'blue', size = zero_line_size) +
  labs(x = 'CLR(Enterococcus) change', y = '') +
  theme_classic() +
  theme(legend.position = 'none') +
  theme(axis.text = element_text( size = 10),
        axis.text.y = element_markdown(),
        plot.background = element_rect(fill='transparent', color=NA), 
        axis.title=element_text(size=10), 
        aspect.ratio=1.5)      
macro_lactose   
```

```{r}
title <- ggdraw() + 
  draw_label(
    "Fig. R2",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    plot.margin = margin(0, 0, 0, 0)
  )


combined <- plot_grid(
  title, macro_lactose,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)+theme(plot.margin = unit(c(0,3,1,1), "cm")) 

ggsave('../data/Fig_R2_macro_lactose_13.png',
      width = 210, height = 157, units = "mm", device = 'png', plot = combined, dpi = 300)  
```

```{r}
# # how many samples have exposure to lactose related stuff in the milk 
# sugar_summary <- full %>% 
#   select(sugar_high:sugar_other) %>% 
#   mutate(any_milk = ifelse(sugar_high > 0 | sugar_low > 0 | sugar_moderate > 0, T, F)) 
#  
# sugar_summary %>% count(any_milk)
```


```{r}
# sugar_summary %>% 
#   gather('type','p2d_ave',sugar_high:sugar_other) %>% 
#   mutate(p2d_ave = 100*p2d_ave) %>% 
#   group_by(type) %>% 
#   ggboxplot(x = 'type', y = 'p2d_ave', add = 'jitter', add.params = list(alpha = 0.2) ) +
#   scale_y_sqrt()
# 
# 
# sugar_summary %>% 
#   gather('type','p2d_ave',sugar_high:sugar_other) %>% 
#   mutate(p2d_ave = 100*p2d_ave) %>% 
#   filter(p2d_ave > 0) %>% 
#   count(type) %>% 
#   mutate(perc = round(n/1009*100,2))
```
